apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-ff
  namespace: ff-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: show-ff
  template:
    metadata:
      labels:
        app: show-ff
    spec:
      containers:
      - name: show-ff
        image: rssnyder/show-ff:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: show-ff
  namespace: ff-test
spec:
  type: LoadBalancer
  selector:
    app: show-ff
  ports:
  - name: http
    port: 80
    targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: show-ff
  namespace: ff-test
spec:
  ingressClassName: nginx
  rules:
    - host: show-ff.k8s.rileysnyder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  show-ff
                port:
                  number: 80
