all:
  vars:
    s3_host: https://s3.cloud.rileysnyder.org
    s3_username: minio
    s3_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65663935643538303430323962343034393831393739393930653532666534356335663137663963
      3663336161303434336234656635346335363335333038360a656336643839353733636539393864
      35393132323163616335343532323938653537313963323935356336656136353236373137616431
      3863653530633030380a616464646233306438626562666534373961636638393466333938623865
      3361
    arch: linux-amd64
    cache_version: v0.2.0
    ticker_version: v2.5.1
  children:
    primary:
      hosts:
        oc0:
          ansible_host: 192.168.100.20
          ansible_user: ubuntu
        oc1:
          ansible_host: 192.168.100.21
          ansible_user: ubuntu
        
    premium:
      hosts:
        oc2:
          ansible_host: 192.168.100.22
          ansible_user: ubuntu
          clients:
#             cryptocrew:
#               name: cryptocrew
#               port: 8001
#               binary: discord-stock-ticker
#               crypto: 4
            alset:
              name: alset
              port: 8002
              binary: discord-stock-ticker
              crypto: 3
            sheepus:
              name: sheepus
              port: 8003
              binary: discord-stock-ticker
              crypto: 2
            sarv-shaktimaan:
              name: sarv-shaktimaan
              port: 8004
              binary: discord-stock-ticker
              crypto: 10
            ender-0:
              name: ender-0
              port: 8005
              binary: discord-stock-ticker
              crypto: 9
            hygge:
              name: hygge
              port: 8006
              binary: discord-stock-ticker
              crypto: 2
            cipher:
              name: cipher
              port: 8007
              binary: discord-stock-ticker
              crypto: 1
            witdawristshot:
              name: witdawristshot
              port: 8008
              binary: discord-stock-ticker
              crypto: 3
            razermanic:
              name: razermanic
              port: 8009
              binary: discord-stock-ticker
              crypto: 4
            aetherean:
              name: aetherean
              port: 8010
              binary: discord-stock-ticker
              crypto: 1
            notzaj:
              name: notzaj
              port: 8011
              binary: discord-stock-ticker
              crypto: 7
#             chillywatermelon:
#               name: chillywatermelon
#               port: 8012
#               binary: discord-stock-ticker
#               crypto: 2
            vectorsix:
              name: vectorsix
              port: 8013
              binary: discord-stock-ticker
              crypto: 1
        oc3:
          ansible_host: 192.168.100.23
          ansible_user: ubuntu
          clients:
            pearson:
              name: pearson
              port: 8001
              binary: discord-stock-ticker
              stock: 2
            modbusmasterofnull:
              name: modbusmasterofnull
              port: 8002
              binary: discord-stock-ticker
              stock: 1
            test:
              name: test
              port: 8005
              binary: test
              crypto: 1
              stock: 1
            jonesbooned:
              name: jonesbooned
              port: 8006
              binary: discord-stock-ticker
              crypto: 1
              stock: 1
            empros:
              name: empros
              port: 8007
              binary: discord-stock-ticker
              stock: 1
            maylian:
              name: maylian
              port: 8008
              binary: discord-stock-ticker
              crypto: 1
              stock: 1
            itsjooeee:
              name: itsjooeee
              port: 8009
              binary: discord-stock-ticker
              crypto: 1
              stock: 1
            cswxg:
              name: cswxg
              port: 8010
              binary: discord-stock-ticker
              crypto: 2
              stock: 1
            traderi:
              name: traderi
              port: 8011
              binary: discord-stock-ticker
              stock: 1
        oc4:
          ansible_host: 192.168.100.24
          ansible_user: ubuntu
          clients:
            jones:
              name: jones
              port: 8001
              binary: discord-stock-ticker
              crypto: 2
              stock: 15
#             deetz:
#               name: deetz
#               port: 8002
#               binary: discord-stock-ticker
#               stock: 5
            professor:
              name: professor
              port: 8003
              binary: discord-stock-ticker
              stock: 3
            ciz:
              name: ciz
              port: 8004
              binary: discord-stock-ticker
              crypto: 3
              stock: 10
            fathom:
              name: fathom
              port: 8005
              binary: discord-stock-ticker
              stock: 4
        oc5:
          ansible_host: 192.168.100.25
          ansible_user: ubuntu
          clients:
            ender-1:
              name: ender-1
              port: 8001
              binary: discord-stock-ticker
              stock: 8
            ender-2:
              name: ender-2
              port: 8002
              binary: discord-stock-ticker
              stock: 8
            ender-3:
              name: ender-3
              port: 8003
              binary: discord-stock-ticker
              stock: 8
            ender-4:
              name: ender-4
              port: 8004
              binary: discord-stock-ticker
              stock: 7
        oc7:
          ansible_host: 192.168.100.27
          ansible_user: ubuntu
          clients:
            drzaius:
              name: drzaius
              port: 8001
              binary: discord-stock-ticker
              sotck: 3
            locupleto:
              name: locupleto
              port: 8002
              binary: discord-stock-ticker
              crypto: 3
              stock: 4
    local:
      hosts:
        kate:
          ansible_host: 192.168.100.10
          ansible_user: riley
        topo:
          ansible_host: 192.168.100.5
          ansible_user: riley
