all:
  vars:
    fiber: 00262586
    s3:
      host: https://s3.rileysnyder.dev
      access_key: isengard
    scrape: 120s
    arch: amd64
    cache_version: v0.5.3
    ticker_version: 3.10.7-beta.1
    extra_dst_args:
    pull: false
    dst_full: true
    clients: {}
    service_env: []
    ansible_user: riley
    extra_packages:
      - git
      - zsh
      - mosh
      - rsync
  children:
    local:
      hosts:
        # zira:
        #   ansible_host: 192.168.0.2
        hurley:
          ansible_host: 192.168.0.3
          arch: arm64
        # octopi:
        #   ansible_host: 192.168.0.36
        # t480:
        #   ansible_host: 192.168.0.4
        cornelius:
          ansible_host: 192.168.0.6
          vars:
            rclone_opts: "-v copy /bucket/backup crypt:bucket/backup -L"
            rclone_utc_hour: 4
        charlie:
          ansible_host: 192.168.0.10
          vars:
            full: false
            rclone_opts: "-v copy /mnt/bulk/k8s/frigate crypt:frigate -L"
            rclone_utc_hour: 6
        jack:
          ansible_host: 192.168.0.11
          vars:
            full: false
        kate:
          ansible_host: 192.168.0.12
          vars:
            full: false
    remote:
      hosts:
        # knapp:
        #   ansible_host: knapp.tail1e5ed.ts.net
        #   vars:
        #     docker_apt_arch: arm64
        #     docker_users:
        #     - riley
        #     - hunter
        zaius:
          ansible_host: 192.168.0.24
    oc:
      vars:
        ansible_user: ubuntu
        iptables: true
        arch: arm64
        extra_dst_args: -frequency=60 -redisAddress="oca0:6379"
        docker_apt_arch: arm64
        docker_users:
        - riley
      hosts:
        oca0:
          ansible_host: 129.146.149.166
          extra_dst_args: -frequency=30 -redisAddress="localhost:6379"
          clients:
            # empros: 8101
            # gerion: 8103
            # cristofollis: 8104
            # sebmonty: 8106
            # pierrotzs: 8108
            # razermanic: 8118
            # hemicrani: 8120
            # canadiangoose: 8127
            # zern: 8128
            # luma: 8129
            # youknowwho: 8132
            # geryatric: 8134
            warriorfight: 8141 # now 0xsteamboat
            # sarvshaktimaan: 8159
            # vvvvteth: 8160
            # soah: 8161
            jonesy: 8162
            ernestas: 8163
            whitemane: 8164
            charmander: 8165
            # auvi: 8166
            # pikapika: 8167
            # mikobu: 8168
            defidope: 8169
            # davinci: 8170
            # danayahoo: 8173
            # skantina2: 8174
            # yamon: 8175
            # tstyabieth: 8176
            # barnakiss: 8177
            cibbers: 8016
            defikraken: 8047
            klaudiuszeth: 8048
            senseilambo: 8043
            wincenty: 8079
            hyperx: 8084
            twade: 8085
            svrebelo: 8205
            cotufa: 8247
            patrick: 8253
            redneb: 8257
            aryaspooks: 8300
            mishaj: 8102
            mastablasta: 8109
            albloshy: 8114
            tavernsideguides: 8115
            pir8radio: 8116
            sai: 8121
            polykoma: 8138
            yunggod: 8140

            huddas: 8200
            
            public: 1000
            jonesbooned: 6969
            ender: 7000
        oca1:
          ansible_host: 129.153.217.210
        oca2:
          ansible_host: 158.101.27.222
          clients:
            # walterjazz: 8003
            # pyroborg: 8004
            # slapu: 8005
            # nicolepatt: 8006
            # torpedo: 8007
            # galaxynick: 8013
            # joppien: 8015
            
            # iwinoliver: 8017
            # ted29up: 8019
            # vttjames: 8026
            # generalorochi: 8033
            # nandobanando: 8035
            # flipstar: 8040
            # joob: 8043
            # scytalex: 8044

            # kingway: 8049
            # dcyeahthatsme: 8161
            # livesquawkaudiotest: 8162
            # malekmalyen: 8167
            # carve: 8168
            # justmoonshot: 0000
        oca3:
          ansible_host: 144.24.58.138
          clients:
            # chaneuwoo: 8022
            # lauty: 8024
            # scylla: 8029
            # proxen: 8030
            # insaneyinyang: 8039
            
            # gomugomuno: 8053
            # professor: 8055
            # ultrap: 8056
            # craafted: 8057
            # revutoadmin: 8065
            # ronson: 8070
            # moectomorrow: 8076
            # smartsharks: 8078
            
            # croissant: 8080
            # iwinned: 8083
            
            # fonziinator: 8086
            # darq: 8087 NEED TO RECLAIM
            # bacon: 0000
        oca4:
          ansible_host: 129.153.95.143
          clients:
            # magux: 8200
            # seven: 8201
            # martc: 8203
            # juffytosegovia: 8204
            
            # pokemonmania: 8206
            # korean: 8210
            # kuri: 8212
            # aleem: 8221
            # kingjung: 8222
            # ik: 8223
            # jackbeck1: 8225
            # mrkookz: 8227
            # inspectorgoole: 8228
            # cookie: 8229
            # whitemanettv: 8230
            # huddas: 8232
            # annetburton: 8233
            # mimz: 8235
            # ringfidev: 8236
            # authority: 8237
            # antoniobruh: 8242
            # rxdo: 8245
            
            # okamihoro: 8256
            
            # metanarrative: 8259
            # kappa: 0000
        oca5:
          ansible_host: 129.146.157.81
          clients:
            # vestro: 8100
            
            # veilleux: 8103
            # cacalillos: 8104
            # veilleuxalt: 8105
            # chakal: 8106
            # bryant: 8108
            
            # mraygo: 8110
            # lucci: 8111
            # hassie: 8112
            
            # fifth: 8117
            # yetik: 8120
            
            # olivia: 8124
            # biggi: 8125
            # matejkocevar: 8132
            # apesenchanter: 8135
            
            # elude: 8141
            # yetik: 0000
            # veilleuxalt: 000
        oca6:
          ansible_host: 144.24.63.75
          ansible_user: riley
        oca7:
          ansible_host: 129.146.43.216
          clients:
