all:
  vars:
    s3:
      host: https://axnsjajcck26.compat.objectstorage.us-phoenix-1.oraclecloud.com
      username: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        36396463343736666533343565313537393637666633396536333831333435366639653331396364
        6137303935356438363833303237646536323132393064340a633535383166336436303266646233
        38363731373563346331376435666363323061633730653337653530316231393261333033333939
        3833343038303637360a646362633937633232303866313765356437306165376631313638316130
        62663231623433653363613664316639316337646461643532353065323033313363346337636533
        3961643064653737666435386336333766396664643932373037
      password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        66373964333933663163383336663435363165663431376538363266633533633064666134333336
        6336363363353239323635376135386461306430316338630a326135613135313035343061616464
        32623336656439323265653439633233333432666431333237363366323637396135313261623733
        3534616666393137640a643063653835643362343533623232323265326266386232396432313961
        30353161646237353530353164613731626137303538313166643662646165353562646132373161
        3565326437383832613863333534343230333538353537336430
    scrape: 120s
    arch: amd64
    cache_version: v0.5.1
    ticker_version: 3.10.0-beta.8
    extra_dst_args:
    pull: false
    internal_net: 192.168.100.0/24
    iptables: false
    clients: {}
  children:
    local:
      hosts:
        kate:
          ansible_host: 192.168.0.61
          ansible_user: riley
        indy:
          ansible_host: 192.168.0.43
          ansible_user: pi
          arch: arm-7
        bigblackbox:
          ansible_host: 10.253.0.1
          ansible_user: root
    oracle:
      vars:
        ansible_user: ubuntu
        iptables: true
      hosts:
        oc0:
          ansible_host: 129.146.252.4
      children:
        oracle_arm:
          vars:
            arch: arm64
          hosts:
            oca7:
              ansible_host: oca7.rileysnyder.org
            oca8:
              ansible_host: oca8.rileysnyder.org
            oca9:
              ansible_host: oca9.rileysnyder.org
        oracle_arm_dst:
          vars:
            arch: arm64
            extra_dst_args: -frequency=10 -redisAddress="192.168.101.35:6379"
          hosts:
            oca0:
              ansible_host: oca0.rileysnyder.org
              extra_dst_args: -frequency=90 -redisAddress="192.168.101.35:6379"
              clients:
                public: 8000
            oca1:
              ansible_host: oca1.rileysnyder.org
              clients:
                bluewaveaudio: 2000
                ender: 3000
            oca2:
              ansible_host: oca2.rileysnyder.org
              clients:
                bugs: 8000
                caedosalt: 8001
                caedos: 8002
                kingkong: 8003
                apexishunter: 8004
                ami: 8008
                matt: 8009
                walterjazz: 8011
                pyroborg: 8017
                shimagunz: 8018
                c4pt4in: 8021
                slapu: 8025
                exus: 8026
                nicolepatt: 8027
                luffyowls: 8029
                torpedo: 8030
                sinister: 8031
                corneliusswaglord: 8033
                sacred: 8034
                black: 8035
                booz: 8036
                joeybjacobson: 8037
                galaxynick: 8038
                gharouk: 8039
                joppien: 8040
                cibbers: 8041
                iwinoliver: 8042
                beuswhale: 9043
                ted29up: 9044
                exochaos: 9045
                mikedee: 9047
                tobiyah: 9048
                mrpiggybank: 9049
                atomical: 9050
                scorpio: 9051
            oca3:
              ansible_host: oca3.rileysnyder.org
              clients:
                magux: 8035
                doyalalexander: 8036
                illu: 8037
                slump: 8040
                velinova: 8041
                seven: 8042
                avalon747: 8043
                kendrickllama: 8048
                martc: 8049
                doglord: 8050
                eriknuke98: 8051
                younggod: 8053
                bass: 8054
                ryanc: 8057
                cryptohimbo: 8060
                bingobango: 8061
                juffytosegovia: 8062
                matan: 8063
                svrebelo: 8064
                scott: 8065
                pokemonmania: 8066
                traderi: 8067
                tuanhm: 8068
                kappa: 8070
                lego: 8071
                korean: 8072
                ugnius: 8073
                kuri: 8074
                bhav: 8075
                degen: 8076
                jwd: 8077
                cnofeusd: 8079
                diglobal: 8080
                krunalamin: 8081
                koolkatz: 8082
                jaden530: 8083
                milow: 8084
                tontondelalune: 8085
                aleem: 8086
                kingjung: 8087
                ik: 8088
                younglex: 8089
                hinverlex: 8090
                jackbeck1: 8091
                miki: 8092
                jacobnfg: 8093
                mrkookz: 8094
                inspectorgoole: 8095
            oca4:
              ansible_host: oca4.rileysnyder.org
              clients:
                pearson: 8018
                modbusmasterofnull: 8019
                jonesbooned: 8020
                empros: 8021
                sfr: 8023
                oracle: 8025
                gerion: 8063
                ty13rrr0ok: 8064
                cristofollis: 8068
                coma: 8069
                wes2: 8070
                rich: 8071
                nzaru: 8072
                sebmonty: 8073
                darthvagitarian: 8075
                themexican: 8076
                pierrotzs: 8077
                ren: 8078
                azing: 8079
                kryxiviaexplorer: 8080
                puremonster: 8082
                a20z: 8083
                kraytoshi: 8084
                iranbgu: 8085
                ridethewav: 8086
                cswxg: 8087
                razermanic: 8088
                ridethewav-alt: 8089
                hemicrani: 8091
                malekmalyen: 8092
                blchon: 8093
                crimsbot: 8094
                malekmalyen-alt: 8095
                gghadid: 8096
                giggity: 8098
                izpawnzin: 8099
                canadiangoose: 8100
                balaji: 8101
                quantasy: 8102
                zern: 8103
                luma: 8104
                noodle: 8105
                juliesos: 8106
                rustumsk: 8107
                jamesath: 8108
                youknowwho: 8109
                wolfman5398: 8112
                geryatric: 8113
                finn: 8115
                sl0thzy: 8116
                freezeframe: 8117
                fridasperax: 8120
                bitmax: 8122
                mekabiel: 8124
                mummy: 8125
                warriorfight: 8126
            oca5:
              ansible_host: oca5.rileysnyder.org
              clients:
                sheepus: 8001
                chillywatermelon: 8003
                hygge: 8004
                cipher: 8005
                aetherean: 8008
                iamcharchar: 8009
                sarv-shaktimaan: 8010
                zooma: 8012
                ionut4a: 8014
                chaneuwoo: 8022
                besseralleine: 8023
                lauty: 8024
                berry: 8025
                lucas: 8027
                niftyplayerone: 8028
                scylla: 8029
                proxen: 8030
                whoisoldgreg: 8031
                stevenc: 8032
                funferret: 8034
                senzi: 8035
                janis: 8036
                pinx: 8037
                cryptostu: 8038
                insaneyinyang: 8039
                draft: 8040
                rimurutempest: 8041
                mrniceguybullybob: 8042
                senseilambo: 8043
                ariyana: 8044
                eisbaer: 8045
                muyaa: 8046
                mrsurf: 8047
                theavgamer: 8048
                rifle: 8052
                gomugomuno: 8053
                thebullishtradr: 8054
                professor: 8055
                ultrap: 8056
                craafted: 8057
                demigod: 8058
                charliebigpetr: 8059
                kiruna: 8060
                josh: 8061
                thedoctor: 8062
                cibbers: 8063
                glaucus: 8064
                revutoadmin: 8065
                kikozl: 8066
            oca6:
              ansible_host: oca6.rileysnyder.org
              clients:
                vestro: 8059
                blooddiamond: 8060
                mishaj: 8062
                veilleux: 8017
                cacalillos: 8018
                wizarddevv: 8020
                veilleuxalt: 8021
                ely: 8022
                kean: 8023
                tomxnoo: 8024
                chakal: 8025
                locke: 8027
                colddoge: 8028
                brhino: 8029
                oneone13: 8030
                hideyoshi: 8031
                hideyoshiphp: 8032
                mattwill: 8033
                jumpman: 8034
                edge: 8035
                thorhammer: 8037
                bryant: 8038
                mastablasta: 8039
                ghost: 8040
                mraygo: 8041
                lucci: 8042
                bundy: 8043
                hassie: 8044
                spamton: 8045
                albloshy: 8046
                tavernsideguides: 8048
                themehrankhan: 8050
                pir8radio: 8051
                fifth: 8052
                jeremyc: 8053
                antonio: 8054
                joshuataylor: 8055
                axiekingdom: 8056
                wordian: 8057
                yetik: 8058
                sai: 8063
                wtffmc: 8064
                marcdomancie: 8065
                olivia: 8066
                revi: 8067
                biggi: 8068
                kas: 8069
                ironcurtaiin: 8070
                tyler: 8071
