all:
  vars:
    s3:
      host: https://s3.cloud.rileysnyder.org
      username: minio
      password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        65663935643538303430323962343034393831393739393930653532666534356335663137663963
        3663336161303434336234656635346335363335333038360a656336643839353733636539393864
        35393132323163616335343532323938653537313963323935356336656136353236373137616431
        3863653530633030380a616464646233306438626562666534373961636638393466333938623865
        3361
    grafana_cloud:
      stack: 254181
      password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35653932303036373834313730313664303930653032333935633635343439376136303636393862
          3165663865343066366633313462383637336564663264340a383363616132613762323235666338
          34656461663534363230326232363432636534623632366562636161646437326331346531366166
          6163633665623963380a313037383537363363313564336266356130353637373536663362633235
          64316330656335623165376133343039333834366231663439363666376130626162326361356630
          66656332633063356561396130396237376364613438383361643063643463323231626435316263
          39653365363733613661373136663561303136393364636265383838613165376530393138333964
          31633934383835323038653832663361316564393032356331356230313862663361363935333166
          36373831616531323638656632316166636364643734353266633836633030666465363933366661
          66646234626430306132636437343038643431626536366230346465353336666632386630393438
          386162653337333464333131363731396437
      user:
        integrations: 207937
        loki: 102940
        prometheus: 207937
    metrics: []
    scrape: 120s
    clients:
    arch: linux-amd64
    cache_version: v0.4.0
    ticker_version: v3.5.1
    extra_dst_args:
    pull: false
    internal_net: 192.168.100.0/24
    iptables: false
    nebula_ca_name: "rileysnyder.org"
    nebula_ca_dir: "~/Documents/nebula/certs"
    nebula_device_config_dir: "~/Documents/nebula/configs"
    nebula_dns: true
    nebula_lighthouse_public_ip: 129.146.252.4
    nebula_lighthouse_private_ip: 192.168.100.1
    nebula_groups: "servers"
    nebula_client_devices:
      - nebula_hostname: "laptop"
        nebula_ip: 192.168.100.3
        nebula_groups: "core,servers,bigblackbox"
        nebula_outbound_firewall_rules: |
          - port: any
            proto: any
            host: any
        nebula_inbound_firewall_rules: |
          - port: any
            proto: any
            host: any
      - nebula_hostname: "phone"
        nebula_ip: 192.168.100.4
        nebula_groups: "core,servers"
        nebula_outbound_firewall_rules: |
          - port: any
            proto: any
            host: any
        nebula_inbound_firewall_rules: |
          - port: any
            proto: any
            host: any
      - nebula_hostname: "tower"
        nebula_ip: 192.168.100.6
        nebula_groups: "servers"
        nebula_outbound_firewall_rules: |
          - port: any
            proto: any
            host: any
        nebula_inbound_firewall_rules: |
          - port: any
            proto: any
            host: any
      - nebula_hostname: "bigblackbox"
        nebula_ip: 192.168.100.7
        nebula_groups: "bigblackbox"
        nebula_outbound_firewall_rules: |
          - port: any
            proto: any
            host: any
        nebula_inbound_firewall_rules: |
          - port: any
            proto: any
            host: any
    nebula_outbound_firewall_rules: |
      - port: any
        proto: any
        host: any
    nebula_inbound_firewall_rules: |
      - port: any
        proto: any
        host: any
  children:
    ocean:
      vars:
        ansible_user: root
        extra_dst_args: -redisAddress="10.108.0.9:6379"
        clients:
      hosts:
        public:
          ansible_host: 192.168.100.50
          nebula_ip: 192.168.100.50
          # metrics:
          #   - discord-stock-ticker-public
          clients:
            public:
              name: public
              port: 8000
        cache:
          ansible_host: 192.168.100.51
          nebula_ip: 192.168.100.51
        do0:
          ansible_host: 142.93.178.78
          nebula_ip: 192.168.100.60
          nebula_hostname: do0
          scrape: 30s
          metrics:
            - discord-stock-ticker
          clients:
            bugs:
              name: bugs
              port: 8000
            hugodzilla:
              name: hugodzilla
              port: 8001
            caedos:
              name: caedos
              port: 8002
            pzyko:
              name: pzyko
              port: 8003
            apexishunter:
              name: apexishunter
              port: 8004
            wil:
              name: wil
              port: 8005
            cheeto:
              name: cheeto
              port: 8006
            bitcoin:
              name: bitcoin
              port: 8007
            ami:
              name: ami
              port: 8008
            matt:
              name: matt
              port: 8009
            nine:
              name: nine
              port: 8010
            walterjazz:
              name: walterjazz
              port: 8011
            magsasaka:
              name: magsasaka
              port: 8012
            quantasy:
              name: quantasy
              port: 8013
            sadi:
              name: sadi
              port: 8014
            chia:
              name: chia
              port: 8015
            relax:
              name: relax
              port: 8016
            pyroborg:
              name: pyroborg
              port: 8017
        do1:
          ansible_host: 68.183.158.212
          nebula_ip: 192.168.100.61
          nebula_hostname: do1
          scrape: 30s
          metrics:
            - discord-stock-ticker
          clients:
            magux:
              name: magux
              port: 8035
            doyalalexander:
              name: doyalalexander
              port: 8036
            illu:
              name: illu
              port: 8037
            asvzla:
              name: asvzla
              port: 8038
            gabster:
              name: gabster
              port: 8039
            slump:
              name: slump
              port: 8040
            polzhou:
              name: polzhou
              port: 8041
            seven:
              name: seven
              port: 8042
            avalon747:
              name: avalon747
              port: 8043
            krunalamin:
              name: krunalamin
              port: 8044
            shadawn:
              name: shadawn
              port: 8045
            miguelaserrao:
              name: miguelaserrao
              port: 8046
            danielzamora87:
              name: danielzamora87
              port: 8047
            kendrickllama:
              name: kendrickllama
              port: 8048
            martc:
              name: martc
              port: 8049
            doglord:
              name: doglord
              port: 8050
            eriknuke98:
              name: eriknuke98
              port: 8051
            oxcel:
              name: oxcel
              port: 8052
            # flipflip:
            #   name: flipflip
            #   port: 8053
            bass:
              name: bass
              port: 8054
            thefuckingleader:
              name: thefuckingleader
              port: 8055
            jb:
              name: jb
              port: 8056
            ryanc:
              name: ryanc
              port: 8057
            traderi:
              name: traderi
              port: 8058
              stock: 1
        do2:
          ansible_host: 161.35.140.92
          nebula_ip: 192.168.100.62
          nebula_hostname: do2
          scrape: 30s
          metrics:
            - discord-stock-ticker
          clients:
            gghadid:
              name: gghadid
              port: 8027
            annetburton:
              name: annetburton
              port: 8028
            cotufa:
              name: cotufa
              port: 8030
            josh:
              name: josh
              port: 8031
            goldern:
              name: goldern
              port: 8032
            chibi:
              name: chibi
              port: 8033    
            jeruhmii:
              name: jeruhmii
              port: 8034
            fathom:
              name: fathom
              port: 8058
            drzaius:
              name: drzaius
              port: 8059
            locupleto:
              name: locupleto
              port: 8060
            captainwowuk:
              name: captainwowuk
              port: 8061
            demigod:
              name: demigod
              port: 8062
            gerion:
              name: gerion
              port: 8063
            ty13rrr0ok:
              name: ty13rrr0ok
              port: 8064
            chococha:
              name: chococha
              port: 8065
            metalwolf:
              name: metalwolf
              port: 8066
            pearson:
              name: pearson
              port: 8018
              stock: 2
            modbusmasterofnull:
              name: modbusmasterofnull
              port: 8019
              stock: 1
            jonesbooned:
              name: jonesbooned
              port: 8020
              crypto: 2
              stock: 3
            empros:
              name: empros
              port: 8021
              stock: 1
            maylian:
              name: maylian
              port: 8022
              crypto: 1
              stock: 1
            sfr:
              name: sfr
              port: 8023
              crypto: 1
            cswxg:
              name: cswxg
              port: 8024
              crypto: 2
              stock: 1
        do3:
          ansible_host: 161.35.128.202
          nebula_ip: 192.168.100.63
          nebula_hostname: do3
          scrape: 30s
          metrics:
            - discord-stock-ticker
          clients:
            alset:
              name: alset
              port: 8000
              crypto: 3
            sheepus:
              name: sheepus
              port: 8001
              crypto: 2
            richardtodd:
              name: richardtodd
              port: 8002
              crypto: 5
            chillywatermelon:
              name: chillywatermelon
              port: 8003
              crypto: 3
            hygge:
              name: hygge
              port: 8004
              crypto: 2
            cipher:
              name: cipher
              port: 8005
              crypto: 2
            witdawristshot:
              name: witdawristshot
              port: 8006
              crypto: 3
            razermanic:
              name: razermanic
              port: 8007
              crypto: 4
            aetherean:
              name: aetherean
              port: 8008
              crypto: 1
            iamcharchar:
              name: iamcharchar
              port: 8009
              crypto: 1
            sarv-shaktimaan:
              name: sarv-shaktimaan
              port: 8010
              crypto: 1
            vectorsix:
              name: vectorsix
              port: 8011
              crypto: 1
            zooma:
              name: zooma
              port: 8012
              crypto: 1
            shotie:
              name: shotie
              port: 8013
              crypto: 1
            ionut4a:
              name: ionut4a
              port: 8014
              crypto: 5
            chaneuwoo:
              name: chaneuwoo
              port: 8022
            besseralleine:
              name: besseralleine
              port: 8023
        do4:
          ansible_host: 161.35.142.197
          nebula_ip: 192.168.100.64
          nebula_hostname: do4
          scrape: 30s
          metrics:
            - discord-stock-ticker
          clients:
            vestro:
              name: vestro
              port: 8059
              stock: 1
            blooddiamond:
              name: blooddiamond
              port: 8060
              stock: 4
            thelastpolarbear:
              name: thelastpolarbear
              port: 8061
              stock: 1
            mishaj:
              name: mishaj
              port: 8062
              crypto: 1
            veilleux:
              name: veilleux
              port: 8017
            cacalillos:
              name: cacalillos
              port: 8018
            nftgaming:
              name: nftgaming
              port: 8019
            wizarddevv:
              name: wizarddevv
              port: 8020
            veilleux-alt:
              name: veilleux-alt
              port: 8021
            ely:
              name: ely
              port: 8022
            kean:
              name: kean
              port: 8023
            tomxnoo:
              name: tomxnoo
              port: 8024
            chakal:
              name: chakal
              port: 8025
            eleducator:
              name: eleducator
              port: 8026
            locke:
              name: locke
              port: 8027
            colddoge:
              name: colddoge
              port: 8028
            brhino:
              name: brhino
              port: 8029
            oneone13:
              name: oneone13
              port: 8030
            hideyoshi:
              name: hideyoshi
              port: 8031
            hideyoshi-php:
              name: hideyoshi-php
              port: 8032
            mattwill:
              name: mattwill
              port: 8033
    oracle_infra:
      vars:
        ansible_user: ubuntu
        iptables: true
        clients:
      hosts:
        oc0:
          dns_domain: cloud
          dns_entry: "*.cloud"
          nebula_ip: 192.168.100.1
          nebula_is_lighthouse: true
          nebula_hostname: lighthouse
        oc1:
          nebula_ip: 192.168.100.21
          nebula_hostname: library
        oc2:
          ansible_host: 150.136.52.66
          nebula_ip: 192.168.100.22
          nebula_hostname: oc2
        oc8:
          ansible_host: 150.136.175.231
          nebula_ip: 192.168.100.28
          nebula_hostname: oc8
        oc9:
          ansible_host: 129.213.121.240
          nebula_ip: 192.168.100.29
          nebula_hostname: oc9
    oracle_dst:
      vars:
        ansible_user: ubuntu
        iptables: true
        clients:
      hosts:
        oc3:
          ansible_host: 150.136.174.234
          nebula_ip: 192.168.100.23
          nebula_hostname: oc3
          scrape: 30s
          metrics:
            - discord-stock-ticker
            # - redis
          clients:
            chartphase:
              name: chartphase
              port: 8000
        oc4:
          ansible_host: 152.70.151.74
          nebula_ip: 192.168.100.24
          nebula_hostname: oc4
          scrape: 30s
          metrics:
            - discord-stock-ticker
            # - redis
          clients:
            emilevz:
              name: emilevz
              port: 8000
              crypto: 44
        oc5:
          ansible_host: 132.226.31.70
          nebula_ip: 192.168.100.25
          nebula_hostname: oc5
          scrape: 30s
          metrics:
            - discord-stock-ticker
            # - redis
          clients:
            bluewaveaudio:
              name: bluewaveaudio
              port: 8000
        oc6:
          ansible_host: 152.67.251.170
          nebula_ip: 192.168.100.26
          nebula_hostname: oc6
          scrape: 30s
          metrics:
            - discord-stock-ticker
            # - redis
          clients:
            ender:
              name: ender
              port: 8000
        oc7:
          ansible_host: 150.230.42.166
          nebula_ip: 192.168.100.27
          nebula_hostname: oc7
          scrape: 30s
          metrics:
            - discord-stock-ticker
            # - redis
          clients:
            jones:
              name: jones
              port: 8000
    local:
      hosts:
        kate:
          nebula_ip: 192.168.100.10
          ansible_user: riley
          nebula_groups: "core,servers,bigblackbox"
          nebula_hostname: kate
          metrics:
            - discord
        droid:
          ansible_host: 192.168.0.11
          nebula_ip: 192.168.100.11
          ansible_user: root
          nebula_hostname: droid
          nebula_arch: linux-arm-7
        sbx0:
          nebula_ip: 192.168.100.12
          ansible_host: 192.168.100.12
          ansible_user: riley
          nebula_hostname: sbx0
