all:
  vars:
    s3_host: https://s3.cloud.rileysnyder.org
    s3_username: minio
    s3_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65663935643538303430323962343034393831393739393930653532666534356335663137663963
      3663336161303434336234656635346335363335333038360a656336643839353733636539393864
      35393132323163616335343532323938653537313963323935356336656136353236373137616431
      3863653530633030380a616464646233306438626562666534373961636638393466333938623865
      3361
    arch: linux-amd64
    cache_version: v0.4.0
    ticker_version: v3.5.0
    loader_version: 833f38ce219bc9e3d4e89fc9095bd0b591ec59a0
    interface: localhost
    db_path: /etc/discord-stock-ticker
  children:
    ocean:
      hosts:
        bluewaveaudio:
          ansible_host: 64.225.31.151
          ansible_user: root
          interface: 192.168.100.61
          clients:
            bluewaveaudio:
              name: bluewaveaudio
              port: 8000
        ender:
          ansible_host: 167.71.185.53
          ansible_user: root
          interface: 192.168.100.62
          clients:
            ender-0:
              name: ender-0
              port: 8000
              crypto: 9
            ender-1:
              name: ender-1
              port: 8001
              stock: 8
            ender-2:
              name: ender-2
              port: 8002
              stock: 8
            ender-3:
              name: ender-3
              port: 8003
              stock: 8
            ender-4:
              name: ender-4
              port: 8004
              stock: 7
        emilevz:
          ansible_host: 167.172.16.200
          ansible_user: root
          interface: 192.168.100.63
          clients:
            emilevz:
              name: emilevz
              port: 8000
              crypto: 44
    oracle_infra:
      hosts:
        oc0:
        oc1:
    oracle_dst:
      hosts:
        oc2:
          interface: 192.168.100.22
          clients:
            alset:
              name: alset
              port: 8000
              crypto: 3
            sheepus:
              name: sheepus
              port: 8001
              crypto: 2
            richardtodd:
              name: richardtodd
              port: 8002
              crypto: 5
            chillywatermelon:
              name: chillywatermelon
              port: 8003
              crypto: 3
            hygge:
              name: hygge
              port: 8004
              crypto: 2
            cipher:
              name: cipher
              port: 8005
              crypto: 2
            witdawristshot:
              name: witdawristshot
              port: 8006
              crypto: 3
            razermanic:
              name: razermanic
              port: 8007
              crypto: 4
            aetherean:
              name: aetherean
              port: 8008
              crypto: 1
            iamcharchar:
              name: iamcharchar
              port: 8009
              crypto: 1
            sarv-shaktimaan:
              name: sarv-shaktimaan
              port: 8010
              crypto: 1
            vectorsix:
              name: vectorsix
              port: 8011
              crypto: 1
            zooma:
              name: zooma
              port: 8012
              crypto: 1
            shotie:
              name: shotie
              port: 8013
              crypto: 1
            ionut4a:
              name: ionut4a
              port: 8014
              crypto: 5
        oc3:
          interface: 192.168.100.23
          clients:
            pearson:
              name: pearson
              port: 8018
              stock: 2
            modbusmasterofnull:
              name: modbusmasterofnull
              port: 8019
              stock: 1
            jonesbooned:
              name: jonesbooned
              port: 8020
              crypto: 2
              stock: 3
            empros:
              name: empros
              port: 8021
              stock: 1
            maylian:
              name: maylian
              port: 8022
              crypto: 1
              stock: 1
            sfr:
              name: sfr
              port: 8023
              crypto: 1
            cswxg:
              name: cswxg
              port: 8024
              crypto: 2
              stock: 1
            traderi:
              name: traderi
              port: 8025
              stock: 1
            vestro:
              name: vestro
              port: 8026
              stock: 1
            meggymoon:
              name: meggymoon
              port: 8027
              stock: 5
              crypto: 2
            blooddiamond:
              name: blooddiamond
              port: 8028
              stock: 4
            thelastpolarbear:
              name: thelastpolarbear
              port: 8029
              stock: 1
            mishaj:
              name: mishaj
              port: 8030
              crypto: 1
        oc4:
          interface: 192.168.100.24
          clients:
            fathom:
              name: fathom
              port: 8032
              stock: 4
            drzaius:
              name: drzaius
              port: 8033
              sotck: 2
            locupleto:
              name: locupleto
              port: 8034
              crypto: 3
              stock: 4
            captainwowuk:
              name: captainwowuk
              port: 8035
              stock: 2
            demigod:
              name: demigod
              port: 8019
              crypto: 3
            gerion:
              name: gerion
              port: 8020
              crypto: 4
            ty13rrr0ok:
              name: ty13rrr0ok
              port: 8021
              crypto: 2
            chococha:
              name: chococha
              port: 8022
              crypto: 4
            metalwolf:
              name: metalwolf
              port: 8023
              crypto: 1
        oc5:
          interface: 192.168.100.25
          clients:
            miguelaserrao:
              name: miguelaserrao
              port: 8000
              crypto: 3
            danielzamora87:
              name: danielzamora87
              port: 8001
              crypto: 2
            kendrickllama:
              name: kendrickllama
              port: 8002
              crypto: 1
            martc:
              name: martc
              port: 8003
              crypto: 1
            doglord:
              name: doglord
              port: 8004
              crypto: 1
            eriknuke98:
              name: eriknuke98
              port: 8005
              crypto: 1
            oxcel:
              name: oxcel
              port: 8006
              crypto: 5
            flipflip:
              name: flipflip
              port: 8007
              crypto: 11
            bass:
              name: bass
              port: 8008
              crypto: 4
            thefuckingleader:
              name: thefuckingleader
              port: 8009
              crypto: 5
            jb:
              name: jb
              port: 8010
              crypto: 2
            ryanc:
              name: ryanc
              port: 8011
              crypto: 2
        oc6:
          interface: 192.168.100.26
          clients:
            magux:
              name: magux
              port: 8001
              crypto: 1
            doyalalexander:
              name: doyalalexander
              port: 8002
              crypto: 10
            illu:
              name: illu
              port: 8003
              crypto: 2
            asvzla:
              name: asvzla
              port: 8004
              crypto: 3
            gabster:
              name: gabster
              port: 8005
              crypto: 2
            slump:
              name: slump
              port: 8006
              crypto: 1
            polzhou:
              name: polzhou
              port: 8007
              crypto: 5
            seven:
              name: seven
              port: 8008
              stock: 2
              crypto: 1
            avalon747:
              name: avalon747
              port: 8024
              crypto: 1
              matic: 1
              gas: 2
            krunalamin:
              name: krunalamin
              port: 8025
              crypto: 1
            shadawn:
              name: shadawn
              port: 8026
              crypto: 3
        oc7:
          ansible_host: 64.225.55.67
          ansible_user: root
          interface: 192.168.100.64
          clients:
            bugs:
              name: bugs
              port: 8027
              crypto: 2
            hugodzilla:
              name: hugodzilla
              port: 8028
              crypto: 6
            caedos:
              name: caedos
              port: 8029
              crypto: 11
            pzyko:
              name: pzyko
              port: 8030
              crypto: 3
            apexishunter:
              name: apexishunter
              port: 8031
              crypto: 2
            wil:
              name: wil
              port: 8032
              crypto: 4
            # ____:
            #   name: ____
            #   port: 8033
            cheeto:
              name: cheeto
              port: 8034
              crypto: 3
            bitcoin:
              name: bitcoin
              port: 8035
              crypto: 9
            ami:
              name: ami
              port: 8013
              crypto: 6
            matt:
              name: matt
              port: 8014
              crypto: 1
            nine:
              name: nine
              port: 8015
              crypto: 1
            walterjazz:
              name: walterjazz
              port: 8016
              crypto: 1
              holders: 1
        zero:
          ansible_host: 45.55.32.145
          ansible_user: root
          interface: 192.168.100.50
          clients:
            magsasaka:
              name: magsasaka
              port: 8035
              crypto: 2
            quantasy:
              name: quantasy
              port: 8036
              crypto: 4
            jeruhmii:
              name: jeruhmii
              port: 8037
              crypto: 2
            sadi:
              name: sadi
              port: 8038
              crypto: 4
            chia:
              name: chia
              port: 8039
              crypto: 1
            relax:
              name: relax
              port: 8040
              crypto: 11
              token: 1
            veilleux:
              name: veilleux
              port: 8041
              crypto: 9
            cacalillos:
              name: cacalillos
              port: 8042
              crypto: 3
            nftgaming:
              name: nftgaming
              port: 8043
              crypto: 4
            wizarddevv:
              name: wizarddevv
              port: 8044
              crypto: 1
            veilleux-alt:
              name: veilleux-alt
              port: 8045
              crypto: 1
            chaneuwoo:
              name: chaneuwoo
              port: 8046
              crypto: 2
            kean:
              name: kean
              port: 8047
              crypto: 6
            tomxnoo:
              name: tomxnoo
              port: 8048
              crypto: 1
            chakal:
              name: chakal
              port: 8049
              crypto: 2
            eleducator:
              name: eleducator
              port: 8050
              crypto: 1
            gghadid:
              name: gghadid
              port: 8051
              crypto: 1
            annetburton:
              name: annetburton
              port: 8052
              crypto: 1
            miguelaserrao:
              name: miguelaserrao
              crypto: 3
              port: 8053
            cotufa:
              name: cotufa
              port: 8054
              crypto: 1
            josh:
              name: josh
              port: 8055
              crypto: 1
            goldern:
              name: goldern
              port: 8056
              crypto: 6
            chibi:
              name: chibi
              port: 8057
              cyrpto: 4
        
    local:
      hosts:
        kate:
          ansible_host: 192.168.100.10
          ansible_user: riley
          interface: 192.168.100.10
          clients:
            discord-stock-ticker:
              name: discord-stock-ticker
              port: 8000
