all:
  vars:
    fiber: 00262586
    s3:
      host: https://s3.rileysnyder.dev
      access_key: isengard
      secret_key: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        37386639636138333031346562343963343531626162326235373234386136666563643231343662
        6162653865363638633834323531353839323963636131340a616335343837323732636537623539
        61646262333430626632643663646566623135316231623065316234366664323762343535323464
        3962333132326336390a653134666430313462373539656635656166323330643464356539373236
        38326139386136323734653631393738643539343361353864343461653630313166
      k8s:
        longhorn:
          access_key: UuGymLEUXCAeh3tG
          secret_key: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            38633661646532646239636333636563626465383935303230373939633864313163373934643635
            3665653233353239393035353461623933356338643764330a386138363438373338383262653164
            63643039376364386164653164356264383666316531383137356362363230393138373965323332
            6136353336656266620a653730643062653439633865363063303833383432633230653430653830
            64313366623731393436333165366366383063303363353232663461363833383863633962326638
            3261613866336535356632386335396565643665623564373961
    scrape: 120s
    arch: amd64
    cache_version: v0.5.3
    ticker_version: 3.10.7-beta.1
    extra_dst_args:
    pull: false
    dst_full: true
    clients: {}
    service_env: []
    ansible_user: riley
    extra_packages:
      - git
      - zsh
      - mosh
      - rsync
  children:
    local:
      hosts:
        zira:
          ansible_host: 192.168.0.2
        indy:
          ansible_host: 192.168.0.12
          arch: armv6
        hurley:
          ansible_host: 192.168.0.3
          arch: arm64
        octopi:
          ansible_host: 192.168.0.36
        t480:
          ansible_host: 192.168.0.4
        cornelius:
          ansible_host: 192.168.0.6
        charlie:
          ansible_host: charlie
        ethan:
          ansible_host: 192.168.0.226
    remote:
      hosts:
        knapp:
          ansible_host: 192.168.0.34
          vars:
            docker_apt_arch: arm64
            docker_users:
            - riley
            - hunter
    oc:
      vars:
        ansible_user: ubuntu
        iptables: true
        arch: arm64
        extra_dst_args: -frequency=60 -redisAddress="oca0:6379"
        docker_apt_arch: arm64
        docker_users:
        - riley
      hosts:
        oca6:
          ansible_host: 144.24.63.75
          ansible_user: riley
        oca1:
          ansible_host: 129.153.217.210
        oca0:
          ansible_host: 129.146.149.166
          extra_dst_args: -frequency=30 -redisAddress="localhost:6379"
          clients:
            empros: 8101
            gerion: 8103
            cristofollis: 8104
            sebmonty: 8106
            pierrotzs: 8108
            razermanic: 8118
            hemicrani: 8120
            canadiangoose: 8127
            zern: 8128
            luma: 8129
            youknowwho: 8132
            geryatric: 8134
            warriorfight: 8141 # now 0xsteamboat
            sarvshaktimaan: 8159
            vvvvteth: 8160
            soah: 8161
            jonesy: 8162
            ernestas: 8163
            whitemane: 8164
            charmander: 8165
            auvi: 8166
            pikapika: 8167
            mikobu: 8168
            defidope: 8169
            davinci: 8170
            twade: 8172
            danayahoo: 8173
            skantina2: 8174
            yamon: 8175
            tstyabieth: 8176
        oca2:
          ansible_host: 158.101.27.222
          clients:
            walterjazz: 8003
            pyroborg: 8004
            slapu: 8005
            nicolepatt: 8006
            torpedo: 8007
            galaxynick: 8013
            joppien: 8015
            cibbers: 8016
            iwinoliver: 8017
            ted29up: 8019
            vttjames: 8026
            generalorochi: 8033
            nandobanando: 8035
            flipstar: 8040
            joob: 8043
            scytalex: 8044
            defikraken: 8047
            klaudiuszeth: 8048
            kingway: 8049
            dcyeahthatsme: 8161
            livesquawkaudiotest: 8162
            malekmalyen: 8167
            carve: 8168
        oca3:
          ansible_host: 144.24.58.138
          clients:
            chaneuwoo: 8022
            lauty: 8024
            scylla: 8029
            proxen: 8030
            insaneyinyang: 8039
            senseilambo: 8043
            gomugomuno: 8053
            professor: 8055
            ultrap: 8056
            craafted: 8057
            revutoadmin: 8065
            ronson: 8070
            moectomorrow: 8076
            smartsharks: 8078
            wincenty: 8079
            croissant: 8080
            iwinned: 8083
        oca4:
          ansible_host: 129.153.95.143
          clients:
            magux: 8200
            seven: 8201
            martc: 8203
            juffytosegovia: 8204
            svrebelo: 8205
            pokemonmania: 8206
            korean: 8210
            kuri: 8212
            aleem: 8221
            kingjung: 8222
            ik: 8223
            jackbeck1: 8225
            mrkookz: 8227
            inspectorgoole: 8228
            cookie: 8229
            whitemanettv: 8230
            huddas: 8232
            annetburton: 8233
            mimz: 8235
            ringfidev: 8236
            authority: 8237
            antoniobruh: 8242
            rxdo: 8245
            cotufa: 8247
            patrick: 8253
            okamihoro: 8256
            redneb: 8257
            metanarrative: 8259
            aryaspooks: 8300
        oca5:
          ansible_host: 129.146.157.81
          clients:
            vestro: 8100
            mishaj: 8102
            veilleux: 8103
            cacalillos: 8104
            veilleuxalt: 8105
            chakal: 8106
            bryant: 8108
            mastablasta: 8109
            mraygo: 8110
            lucci: 8111
            hassie: 8112
            albloshy: 8114
            tavernsideguides: 8115
            pir8radio: 8116
            fifth: 8117
            yetik: 8120
            sai: 8121
            olivia: 8124
            biggi: 8125
            matejkocevar: 8132
            apesenchanter: 8135
            polykoma: 8138
            yunggod: 8140
            elude: 8141
        oca7:
          ansible_host: 129.146.43.216
          clients:
            public: 1000
            jonesbooned: 6969
            ender: 7000
