all:
  vars:
    fiber: 00262586
    s3:
      host: https://s3.rileysnyder.org
      access_key: isengard
      secret_key: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        39333637633331363736366461383232333864663530313766653261333435303065633432333563
        3162663764306263633331306565623865626266616335360a396430666265306332376538353566
        33316231643363313339306432313461366463313536396461343465366663653433613262373838
        6333626132336637310a343735363563313662326266386664636665643631326130643663616166
        33363933353864313132316433306564626230666530396437386265363137316364623834313430
        3964313138353763363935383138363663646632393834613034
    defined_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33613332643365306439623762373934373638373832643931303964346535303238333564636437
          3164633233323266323836613064303566336266666266360a616466623431386664356238333364
          33653264363636363638633635396463626163616634356564643563366631383537323037613238
          6635316265393362350a393239393864663835633466616365306434306535613439353036333533
          63616639613136666635366235376561396666393035616235393434633932653665393239343530
          39636466336637623837366438643435353631363266343064306366353662356362396138336530
          34356565343364613732303631636134313231353939663333643232653364613032343239663930
          39633762343330653163333633316535303863373463346238383765346330303035643862633731
          3735
    tailscale_authkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36646630363162626363383935383035343338353837343132386639383534346434613635626533
          6363323734623233663032303630393339303531393036350a386137396433396563313934636332
          38666337316130336633623536373364333665666139323263643336336539656261313437396533
          6335643861363465650a383539653664336162656566316634376361316562653462616530396163
          36663031376662663164393764663837633334663865643663653637653635363236656337633566
          3933666138393165656365366636643932653666653133613965
    apex_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61323861313564303165303461616131366230616338326434633833643663336136326431373362
          3263336463653835333231373631646164393062626135610a363265626639373731613738386534
          39393133333136623261303666356564616432333865373536663133326234616432303732366263
          6133326231346666610a313633346133313433616435303831666364333564623037373366376361
          34353464306637666338653938313237353238336661613532323139313064633433613063303739
          32616561633737643466636664376366643665303333633839393932633538643034353165653930
          333439633731636637646263336563306532
    scrape: 120s
    arch: amd64
    cache_version: v0.5.1
    ticker_version: 3.10.0-beta.10
    extra_dst_args:
    pull: false
    dst_full: true
    internal_net: 192.168.100.0/24
    iptables: false
    clients: {}
  children:
    local:
      hosts:
        kate:
        charlie:
    oracle:
      vars:
        ansible_user: ubuntu
        iptables: true
      hosts:
        oc0:
          ansible_host: 129.146.252.4
      children:
        oracle_arm:
          vars:
            arch: arm64
          hosts:
            oca7:
              ansible_host: oca7.rileysnyder.org
            oca8:
              ansible_host: oca8.rileysnyder.org
            oca9:
              ansible_host: oca9.rileysnyder.org
        oracle_arm_dst:
          vars:
            arch: arm64
            extra_dst_args: -frequency=10 -redisAddress="192.168.101.35:6379"
          hosts:
            oca0:
              ansible_host: oca0.rileysnyder.org
              extra_dst_args: -frequency=90 -redisAddress="192.168.101.35:6379"
              clients:
                public: 8000
            oca1:
              ansible_host: oca1.rileysnyder.org
              clients:
                bluewaveaudio: 2000
                ender: 3000
            oca2:
              ansible_host: oca2.rileysnyder.org
              clients:
                bugs: 8000
                kingkong: 8003
                apexishunter: 8004
                ami: 8008
                # matt: 8009
                walterjazz: 8011
                pyroborg: 8017
                shimagunz: 8018
                c4pt4in: 8021
                slapu: 8025
                exus: 8026
                nicolepatt: 8027
                luffyowls: 8029
                torpedo: 8030
                sinister: 8031
                corneliusswaglord: 8033
                sacred: 8034
                black: 8035
                booz: 8036
                joeybjacobson: 8037
                galaxynick: 8038
                gharouk: 8039
                joppien: 8040
                cibbers: 8041
                iwinoliver: 8042
                beuswhale: 9043
                ted29up: 9044
                exochaos: 9045
                mikedee: 9047
                tobiyah: 9048
                mrpiggybank: 9049
                atomical: 9050
                scorpio: 9051
                vttjames: 9052
                cosmo: 9053
                scienceoflearning: 9054
                scarystabber: 9055
                juicyx: 9057
                ai: 9058
                primooo: 9059
                # pandaaaa: 9060
                # joshyboy: 9061
                generalorochi: 9062
                jhake: 9063
                sheriff: 9064
                nandobanando: 9065
                justmoonshot: 9066
                # dother: 9067
                domi: 9068
                dusk: 9069
                erimyth: 9070
                vladelonbank: 9071
                sirhodlslong: 9072
                potatoy: 9073
            oca3:
              ansible_host: oca3.rileysnyder.org
              clients:
                magux: 8035
                doyalalexander: 8036
                # illu: 8037
                slump: 8040
                velinova: 8041
                seven: 8042
                avalon747: 8043
                kendrickllama: 8048
                martc: 8049
                # doglord: 8050
                eriknuke98: 8051
                younggod: 8053
                bass: 8054
                cryptohimbo: 8060
                bingobango: 8061
                juffytosegovia: 8062
                matan: 8063
                svrebelo: 8064
                scott: 8065
                pokemonmania: 8066
                traderi: 8067
                # tuanhm: 8068
                kappa: 8070
                lego: 8071
                korean: 8072
                ugnius: 8073
                kuri: 8074
                bhav: 8075
                degen: 8076
                jwd: 8077
                cnofeusd: 8079
                diglobal: 8080
                krunalamin: 8081
                koolkatz: 8082
                jaden530: 8083
                milow: 8084
                tontondelalune: 8085
                aleem: 8086
                kingjung: 8087
                ik: 8088
                # younglex: 8089
                hinverlex: 8090
                jackbeck1: 8091
                miki: 8092
                jacobnfg: 8093
                mrkookz: 8094
                inspectorgoole: 8095
                bossppap: 8096
                cookie: 8097
                whitemanettv: 8098
                elexier: 8099
                coa: 8100
                huddas: 8101
                annetburton: 8102
                0xkien: 8103
                mimz: 8104
                ringfidev: 8105
                authority: 8106
                merc: 8107
                blackninja: 8108
                phteven: 8109
                kat: 8110
                antoniobruh: 8111
                funhunter: 8112
                ffgvlad: 8113
                rxdo: 8114
            oca4:
              ansible_host: oca4.rileysnyder.org
              clients:
                pearson: 8018
                modbusmasterofnull: 8019
                jonesbooned: 8020
                empros: 8021
                sfr: 8023
                oracle: 8025
                gerion: 8063
                ty13rrr0ok: 8064
                cristofollis: 8068
                coma: 8069
                wes2: 8070
                rich: 8071
                nzaru: 8072
                sebmonty: 8073
                darthvagitarian: 8075
                themexican: 8076
                pierrotzs: 8077
                ren: 8078
                azing: 8079
                kryxiviaexplorer: 8080
                puremonster: 8082
                a20z: 8083
                kraytoshi: 8084
                iranbgu: 8085
                ridethewav: 8086
                cswxg: 8087
                razermanic: 8088
                ridethewav-alt: 8089
                hemicrani: 8091
                malekmalyen: 8092
                blchon: 8093
                crimsbot: 8094
                malekmalyen-alt: 8095
                gghadid: 8096
                giggity: 8098
                izpawnzin: 8099
                canadiangoose: 8100
                balaji: 8101
                quantasy: 8102
                zern: 8103
                luma: 8104
                noodle: 8105
                juliesos: 8106
                rustumsk: 8107
                # jamesath: 8108
                youknowwho: 8109
                wolfman5398: 8112
                geryatric: 8113
                finn: 8115
                sl0thzy: 8116
                fridasperax: 8120
                bitmax: 8122
                mekabiel: 8124
                mummy: 8125
                warriorfight: 8126
                honkie: 8128
                kenny: 8129
                sj: 8131
                birdperson: 8132
                dcshadow: 8133
                jeremyyy: 8134
                kozaki: 8136
                porkiie: 8137
                0xjimmy: 8138
                zippy: 8139 #delete
                con: 8141
                diogofromtheblock: 8142
                jakemiddy: 8143
                darkedu: 8144
                nopal: 8145
                r0b1n: 8146
                blauersamt: 8147
                owo: 8148
                umar: 8149
                dcyeahthatsme: 8150
            oca5:
              ansible_host: oca5.rileysnyder.org
              clients:
                sheepus: 8001
                chillywatermelon: 8003
                hygge: 8004
                cipher: 8005
                aetherean: 8008
                iamcharchar: 8009
                sarv-shaktimaan: 8010
                zooma: 8012
                # ionut4a: 8014
                chaneuwoo: 8022
                besseralleine: 8023
                lauty: 8024
                berry: 8025
                lucas: 8027
                niftyplayerone: 8028
                scylla: 8029
                proxen: 8030
                whoisoldgreg: 8031
                stevenc: 8032
                funferret: 8034
                senzi: 8035
                janis: 8036
                pinx: 8037
                cryptostu: 8038
                insaneyinyang: 8039
                draft: 8040
                rimurutempest: 8041
                mrniceguybullybob: 8042
                senseilambo: 8043
                ariyana: 8044
                eisbaer: 8045
                muyaa: 8046
                mrsurf: 8047
                theavgamer: 8048
                rifle: 8052
                gomugomuno: 8053
                thebullishtradr: 8054
                professor: 8055
                ultrap: 8056
                craafted: 8057
                demigod: 8058
                charliebigpetr: 8059
                kiruna: 8060
                josh: 8061
                thedoctor: 8062
                cibbers: 8063
                glaucus: 8064
                revutoadmin: 8065
                # kikozl: 8066
                bacon: 8067
                ernesto50: 8068
                dunders: 8069
                ronson: 8070
                ger: 8071
                kitsune: 8072
            oca6:
              ansible_host: oca6.rileysnyder.org
              clients:
                vestro: 8059
                blooddiamond: 8060
                mishaj: 8062
                veilleux: 8017
                cacalillos: 8018
                wizarddevv: 8020
                veilleuxalt: 8021
                tomxnoo: 8024
                chakal: 8025
                locke: 8027
                colddoge: 8028
                brhino: 8029
                oneone13: 8030
                hideyoshi: 8031
                hideyoshiphp: 8032
                mattwill: 8033
                jumpman: 8034
                edge: 8035
                thorhammer: 8037
                bryant: 8038
                mastablasta: 8039
                ghost: 8040
                mraygo: 8041
                lucci: 8042
                bundy: 8043
                hassie: 8044
                spamton: 8045
                albloshy: 8046
                tavernsideguides: 8048
                themehrankhan: 8050
                pir8radio: 8051
                fifth: 8052
                jeremyc: 8053
                antonio: 8054
                joshuataylor: 8055
                axiekingdom: 8056
                wordian: 8057
                yetik: 8058
                sai: 8063
                wtffmc: 8064
                marcdomancie: 8065
                olivia: 8066
                revi: 8067
                biggi: 8068
                kas: 8069
                ironcurtaiin: 8070
                tyler: 8071
                djun: 8073
                mb11: 8075
                yvan: 8076
                chainjames: 8077
                matejkocevar: 8078
                necro: 8079
                sonicflare: 8080
                syk: 8081
                brike: 8082
