all:
  vars:
    s3_host: https://s3.cloud.rileysnyder.org
    s3_username: minio
    s3_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65663935643538303430323962343034393831393739393930653532666534356335663137663963
      3663336161303434336234656635346335363335333038360a656336643839353733636539393864
      35393132323163616335343532323938653537313963323935356336656136353236373137616431
      3863653530633030380a616464646233306438626562666534373961636638393466333938623865
      3361
    arch: linux-amd64
    cache_version: v0.2.0
    ticker_version: v2.7.2
    interface: localhost
  children:
    oracle_infra:
      hosts:
        oc0:
        oc1:
    oracle_dst:
      hosts:
        oc2:
          clients:
            alset:
              name: alset
              port: 8002
              crypto: 3
            sheepus:
              name: sheepus
              port: 8003
              crypto: 2
            ender-0:
              name: ender-0
              port: 8005
              crypto: 9
            hygge:
              name: hygge
              port: 8006
              crypto: 2
            cipher:
              name: cipher
              port: 8007
              crypto: 1
              holders: 1
            witdawristshot:
              name: witdawristshot
              port: 8008
              crypto: 3
            razermanic:
              name: razermanic
              port: 8009
              crypto: 4
            aetherean:
              name: aetherean
              port: 8010
              crypto: 1
            notzaj:
              name: notzaj
              port: 8011
              crypto: 7
            vectorsix:
              name: vectorsix
              port: 8013
              crypto: 1
            zooma:
              name: zooma
              port: 8014
              crypto: 1
            cccgs:
              name: cccgs
              port: 8015
              crypto: 1
            matt:
              name: matt
              port: 8016
              crypto: 1
            nine:
              name: nine
              port: 8017
              crypto: 1
            walterjazz:
              name: walterjazz
              port: 8018
              crypto: 1
              holders: 1
        oc3:
          clients:
            pearson:
              name: pearson
              port: 8001
              stock: 2
            modbusmasterofnull:
              name: modbusmasterofnull
              port: 8002
              stock: 1
            empros:
              name: empros
              port: 8007
              stock: 1
            maylian:
              name: maylian
              port: 8008
              crypto: 1
              stock: 1
            itsjooeee:
              name: itsjooeee
              port: 8009
              crypto: 1
              stock: 1
            cswxg:
              name: cswxg
              port: 8010
              crypto: 2
              stock: 1
            traderi:
              name: traderi
              port: 8011
              stock: 1
            vestro:
              name: vestro
              port: 8012
              stock: 1
            meggymoon:
              name: meggymoon
              port: 8013
              stock: 5
              crypto: 2
        oc4:
          clients:
            professor:
              name: professor
              port: 8003
              stock: 3
            ciz:
              name: ciz
              port: 8004
              crypto: 3
              stock: 10
            fathom:
              name: fathom
              port: 8005
              stock: 4
            drzaius:
              name: drzaius
              port: 8006
              sotck: 3
            locupleto:
              name: locupleto
              port: 8007
              crypto: 3
              stock: 4
        oc5:
          interface: 192.168.100.25
          clients:
            ender-1:
              name: ender-1
              port: 8001
              stock: 8
            ender-2:
              name: ender-2
              port: 8002
              stock: 8
            ender-3:
              name: ender-3
              port: 8003
              stock: 8
            ender-4:
              name: ender-4
              port: 8004
              stock: 7
        oc6:
          interface: 192.168.100.26
          clients:
            jones:
              name: jones
              port: 8001
              crypto: 2
              stock: 16
        oc7:
          clients:
            drnodoz0-0:
              name: drnodoz0-0
              port: 8001
              stock: 8
            drnodoz0-1:
              name: drnodoz0-1
              port: 8002
              stock: 9
    local:
      hosts:
        topo:
        kate:
        indy:
        quill:
