all:
  vars:
    s3_host: https://s3.cloud.rileysnyder.org
    s3_username: minio
    s3_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65663935643538303430323962343034393831393739393930653532666534356335663137663963
      3663336161303434336234656635346335363335333038360a656336643839353733636539393864
      35393132323163616335343532323938653537313963323935356336656136353236373137616431
      3863653530633030380a616464646233306438626562666534373961636638393466333938623865
      3361
  children:
    premium:
      hosts:
        oc2:
          ansible_host: 192.168.100.22
          ansible_user: ubuntu
          clients:
            locupleto:
              name: locupleto
              port: 8001
              binary: discord-stock-ticker
            aetherean:
              name: aetherean
              port: 8003
              binary: discord-stock-ticker
            test:
              name: test
              port: 8002
              binary: test
            jonesbooned:
              name: jonesbooned
              port: 8004
              binary: test
            empros:
              name: empros
              port: 8005
              binary: discord-stock-ticker
            luckyluc:
              name: luckyluc
              port: 8006
              binary: discord-stock-ticker
        oc3:
          ansible_host: 192.168.100.23
          ansible_user: ubuntu
          clients:
            drzaius:
              name: drzaius
              port: 8003
              binary: discord-stock-ticker
            witdawristshot:
              name: witdawristshot
              port: 8004
              binary: discord-stock-ticker
            pearson:
              name: pearson
              port: 8001
              binary: discord-stock-ticker
            razermanic:
              name: razermanic
              port: 8002
              binary: discord-stock-ticker
        oc4:
          ansible_host: 192.168.100.24
          ansible_user: ubuntu
          clients:
            ciz:
              name: ciz
              port: 8004
              binary: discord-stock-ticker
            professor:
              name: professor
              port: 8003
              binary: discord-stock-ticker
            deetz:
              name: deetz
              port: 8002
              binary: discord-stock-ticker
            jones:
              name: jones
              port: 8001
              binary: discord-stock-ticker
        oc5:
          ansible_host: 192.168.100.25
          ansible_user: ubuntu
          clients:
            cryptocrew:
              name: cryptocrew
              port: 8003
              binary: discord-stock-ticker
            sarv-shaktimaan:
              name: sarv-shaktimaan
              port: 8002
              binary: discord-stock-ticker
            sheepus:
              name: sheepus
              port: 8004
              binary: discord-stock-ticker
        oc7:
          ansible_host: 192.168.100.27
          ansible_user: ubuntu
          clients:
            alset:
              name: alset
              port: 8001
              binary: discord-stock-ticker
    local:
      hosts:
        kate:
          ansible_host: 192.168.100.10
          ansible_user: riley
        topo:
          ansible_host: 192.168.100.2
          ansible_user: riley
