apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate-stats
  namespace: frigate
spec:
  selector:
    matchLabels:
      app: frigate-stats
  replicas: 1
  template:
    metadata:
      labels:
        app: frigate-stats
    spec:
      containers:
      - name: frigate-stats
        image: rhysbailey/prometheus-frigate-exporter
        env:
        - name: FRIGATE_STATS_URL
          value: http://frigate.frigate.svc.cluster.local/api/stats
        ports:
        - name:  metrics
          containerPort: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: frigate-stats
  namespace: frigate
spec:
  type: LoadBalancer
  selector:
    app: frigate-stats
  ports:
  - name: metrics
    port: 80
    targetPort: metrics

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: frigate-stats
  namespace: frigate
spec:
  selector:
    matchLabels:
      app: frigate-stats
  podMetricsEndpoints:
  - port: metrics