fullnameOverride: frigate
service:
  type: LoadBalancer
  port: 80
config: |
  mqtt:
    host: "mosquitto.mosquitto.svc.cluster.local"
    port: 1883
  database: 
    path: /media/frigate.db
  cameras:
    back:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.97:554/h264Preview_01_main
            roles:
              - detect
      detect:
        width: 2560
        height: 1920
      record:
        enabled: true
    louie:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.98:554/h264Preview_01_main
            roles:
      record:
        enabled: false
    front:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.99:554/h264Preview_01_main
            roles:
              - detect
      detect:
        width: 2560
        height: 1440
      record:
        enabled: true
    roam:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.96:554/h264Preview_01_main
            roles:
              - detect
      detect:
        width: 1280
        height: 720
  snapshots:
    enabled: True
    timestamp: True
    retain:
      default: 30
      objects:
        person: 30
extraVolumes:
  - name: media
    hostPath:
      path: /mnt/bulk/k8s/frigate
extraVolumeMounts:
  - name: media
    mountPath: /media
    subPath: media
nodeSelector:
  kubernetes.io/hostname: charlie