fullnameOverride: frigate
service:
  type: LoadBalancer
  port: 80
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "frigate"
    external-dns.alpha.kubernetes.io/hostname: frigate.r.ss
config: |
  mqtt:
    host: "mosquitto.mosquitto"
    port: 1883
  database: 
    path: /media/frigate.db
  detectors:
    coral:
      type: edgetpu
      device: usb
  go2rtc:
    streams:
      back: 
        - "ffmpeg:http://192.168.0.97/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>#video=copy#audio=copy#audio=opus"
      back_sub: 
        - "ffmpeg:http://192.168.0.97/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>"
      roam: 
        - "ffmpeg:http://192.168.0.96/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>#video=copy#audio=copy#audio=opus"
      roam_sub: 
        - "ffmpeg:http://192.168.0.96/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>"
  cameras:
    back:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/back?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      detect:
        width: 2560
        height: 1920
      record:
        enabled: true
        events:
          required_zones:
          - sidewalkcorner
          - sidewalk
          - door
      snapshots:
        required_zones:
          - sidewalkcorner
          - sidewalk
          - door
      zones:
        sidewalkcorner:
          coordinates: 1079,797,1087,858,1280,875,1289,659,1176,668
          objects:
            - person
        sidewalk:
          coordinates: 0,764,716,747,716,877,0,961
          objects:
            - person
        door:
          coordinates: 1579,680,1563,902,1631,918,1668,872,1672,682
          objects:
            - person
            - dog
      objects:
        track:
          - person
          - dog
    louie:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.98:554/h264Preview_01_main
      record:
        enabled: false
      detect:
        enabled: false
    front:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.99:554/h264Preview_01_main
            roles:
              - detect
      detect:
        width: 2560
        height: 1440
      objects:
        mask:
          - 2330,901,2291,1440,2003,1440,1921,1120,2140,550
      motion:
        mask:
          - 2330,901,2291,1440,2003,1440,1921,1120,2140,550
      record:
        enabled: true
    roam:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/roam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/roam_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      detect:
        width: 2560
        height: 1920
      record:
        enabled: true
    garage:
      ffmpeg:
        inputs:
          - path: rtsp://wyze-bridge:8554/garage-door
            roles:
              - detect
      record:
        enabled: true
  snapshots:
    enabled: True
    timestamp: True
    retain:
      default: 30
      objects:
        person: 30
extraVolumes:
  - name: media
    hostPath:
      path: /mnt/bulk/k8s/frigate
extraVolumeMounts:
  - name: media
    mountPath: /media
    subPath: media
nodeSelector:
  kubernetes.io/hostname: charlie
coral:
  enabled: true
  hostPath: /dev/bus/usb
resources:
  requests:
    cpu: 1500m
    memory: 2Gi