fullnameOverride: frigate
service:
  type: LoadBalancer
  port: 80
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "frigate"
config: |
  mqtt:
    host: "mosquitto.mosquitto"
    port: 1883
  database: 
    path: /media/frigate.db
  detectors:
    coral:
      type: edgetpu
      device: usb
  go2rtc:
    streams:
      back: 
        - "ffmpeg:http://192.168.0.97/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>#video=copy#audio=copy#audio=opus"
      back_sub: 
        - "ffmpeg:http://192.168.0.97/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>"
      # roam: 
      #   - "ffmpeg:http://192.168.0.96/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>#video=copy#audio=copy#audio=opus"
      # roam_sub: 
      #   - "ffmpeg:http://192.168.0.96/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>"
  cameras:
    back:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/back?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      detect:
        width: 2560
        height: 1920
      record:
        enabled: true
    louie:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.98:554/h264Preview_01_main
      record:
        enabled: false
      detect:
        enabled: false
    front:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.99:554/h264Preview_01_main
            roles:
              - detect
      detect:
        width: 2560
        height: 1440
      record:
        enabled: true
    roam:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/roam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/roam_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      detect:
        width: 2560
        height: 1920
      record:
        enabled: true
    garage:
      ffmpeg:
        inputs:
          - path: rtsp://wyze-bridge:8554/garage-door
            roles:
              - detect
      record:
        enabled: true
  snapshots:
    enabled: True
    timestamp: True
    retain:
      default: 30
      objects:
        person: 30
extraVolumes:
  - name: media
    hostPath:
      path: /mnt/bulk/k8s/frigate
extraVolumeMounts:
  - name: media
    mountPath: /media
    subPath: media
nodeSelector:
  kubernetes.io/hostname: charlie
coral:
  enabled: true
  hostPath: /dev/bus/usb
resources:
  requests:
    cpu: 1500m
    memory: 2Gi