apiVersion: v1
kind: Namespace
metadata:
  name: hp-movie-picker

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hp-movie-picker
  namespace: hp-movie-picker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hp-movie-picker
  template:
    metadata:
      labels:
        app: hp-movie-picker
    spec:
      containers:
      - name: hp-movie-picker
        image: rssnyder/harry-potter-picker
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hp-movie-picker
  namespace: hp-movie-picker
spec:
  type: LoadBalancer
  selector:
    app: hp-movie-picker
  ports:
  - name: http
    port: 80
    targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hp-movie-picker
  namespace: hp-movie-picker
spec:
  ingressClassName: nginx
  rules:
    - host: harry-potter-movie-picker.k8s.rileysnyder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  hp-movie-picker
                port:
                  number: 80
