apiVersion: v1
kind: Namespace
metadata:
  name: pg-admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin
  namespace: pg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      imagePullSecrets:
      - name: ghcr-token
      containers:
      - name: api
        image: dpage/pgadmin4:8
        imagePullPolicy: IfNotPresent
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@dndgenerator.io"
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-admin
              key: PGADMIN_DEFAULT_PASSWORD
        ports:
        - name: webui
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pg-admin
  namespace: pg-admin
spec:
  type: LoadBalancer
  selector:
    app: pg-admin
  ports:
  - name: webui
    port: 80
    targetPort: webui

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pg-admin
  namespace: pg-admin
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "pg-admin"
    external-dns.alpha.kubernetes.io/hostname: pg-admin.r.ss
spec:
  ingressClassName: nginx
  rules:
    - host: pg-admin.k8s.rileysnyder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  pg-admin
                port:
                  number: 80
