apiVersion: v1
kind: Namespace
metadata:
  name: dnd-generator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnd-generator-api
  namespace: dnd-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnd-generator-api
  template:
    metadata:
      labels:
        app: dnd-generator-api
    spec:
      imagePullSecrets:
      - name: ghcr-token
      containers:
      - name: api
        image: ghcr.io/rssnyder/dnd-generator:0.0.0-beta.5
        imagePullPolicy: IfNotPresent
        env:
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: PG_PASSWORD
        - name: PG_HOST
          value: "192.168.0.3"
        - name: PG_USER
          value: dm
        - name: PG_DB
          value: dndgenerator
        envFrom:
        - configMapRef:
            name: dnd-generator-api-env
        ports:
        - name: api
          containerPort: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dnd-generator-api
  namespace: dnd-generator
spec:
  selector:
    matchLabels:
      app: dnd-generator-api
  podMetricsEndpoints:
  - port: api

---
apiVersion: v1
kind: Service
metadata:
  name: dnd-generator-api
  namespace: dnd-generator
spec:
  type: LoadBalancer
  selector:
    app: dnd-generator-api
  ports:
  - name: api
    port: 80
    targetPort: api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dnd-generator-api
  namespace: dnd-generator
spec:
  ingressClassName: nginx
  rules:
    - host: dnd-generator.k8s.rileysnyder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  dnd-generator-api
                port:
                  number: 80

