apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: coder
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: webui
          containerPort: 8080
        volumeMounts:
        - name: home
          mountPath: /home/coder
        - name: dind-vol
          mountPath: /var/run
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-vol
            mountPath: /var/run
      volumes:
      - name: dind-vol
        emptyDir:
      - name: home
        persistentVolumeClaim:
          claimName: coder

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
  ports:
  - name: webui
    port: {{ .Values.service.port }}
    targetPort: webui

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}

{{ if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/websocket-services: {{ .Values.app }}
    nginx.org/server-snippets: |
      location / {
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ .Values.app }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}

{{ if .Values.sa.cluster_admin }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namespace }}-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}