apiVersion: batch/v1
kind: Job
metadata:
  name: rsync
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: rsync
        image: rssnyder/rsync
        command: ["rsync", "-varP",  "/bin/", "/tmp/"]
