---
version: "3"
services:

  caddy:
    image: rssnyder/caddy-digitalocean
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - 80:80
    #   - 443:443
    #   - "443:443/udp"
    volumes:
      - $APPDATA/Caddyfile:/etc/caddy/Caddyfile:r

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    volumes:
      - $APPDATA/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
