apiVersion: v1
kind: Namespace
metadata:
  name: syncthing

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      nodeName: charlie
      containers:
      - name: syncthing
        image: linuxserver/syncthing:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/Chicago
        ports:
        - name: webui
          containerPort: 8384
        - containerPort: 22000
          protocol: TCP
        - containerPort: 22000
          protocol: UDP
        - containerPort: 21027
          protocol: UDP
        volumeMounts:
        - name: data
          mountPath: /data/appdata
        - name: config
          mountPath: /config
      volumes:
      - name: data
        hostPath:
          path: /mnt/bulk/k8s/syncthing/data
      - name: config
        hostPath:
          path: /mnt/bulk/k8s/syncthing/config

---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: syncthing
spec:
  type: LoadBalancer
  selector:
    app: syncthing
  ports:
  - name: webui
    port: 80
    targetPort: webui
