apiVersion: v1
kind: Namespace
metadata:
  name: mosquitto

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app: mosquitto
data:
  ALLOW_UNSECURED_MODE: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: mosquitto
        ports:
        - name: mqtt
          containerPort: 1883
        - name: other
          containerPort: 9001
        volumeMounts:
        - name: mosquitto
          mountPath: /mosquitto
      volumes:
      - name: mosquitto
        persistentVolumeClaim:
          claimName: mosquitto

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100k

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mosquitto.r.ss
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    port: 1883
    targetPort: mqtt
