---
apiVersion: v1
kind: Namespace
metadata:
  name: discord-bot

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: ghcr.io/rssnyder/discord-bot:0.0.6
        imagePullPolicy: IfNotPresent
        env:
        - name: NICKNAME
          value: k3s
        - name: REFRESH
          value: "3600"
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot
              key: token
