apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.downloads.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.downloads.pvc.size }}
