apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-env
  namespace: {{ .Values.namespace }}
  labels:
    app: qbittorrent
data:
  WEBUI_PORT: {{ .Values.qbittorrent.port }}
  PUID: {{ .Values.PUID }}
  PGID: {{ .Values.PGID }}
  TZ: {{ .Values.timezone }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: {{ .Values.qbittorrent.image }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: qbittorrent-env
        ports:
        - name: webui
          containerPort: {{ .Values.qbittorrent.port }}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent

---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.qbittorrent.service.type }}
  selector:
    app: qbittorrent
  ports:
  - name: webui
    port: {{ .Values.qbittorrent.service.port }}
    targetPort: webui

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.qbittorrent.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.qbittorrent.pvc.size }}
  {{ if .Values.qbittorrent.pvc.useExistingVolume }}
  volumeName: {{ .Values.qbittorrent.pvc.useExistingVolume }}
  {{- end }}

{{ if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: qbittorrent.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  qbittorrent
                port:
                  number: {{ .Values.qbittorrent.service.port }}
{{- end }}