apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-env
  namespace: {{ .Values.namespace }}
  labels:
    app: radarr
data:
  WEBUI_PORT: {{ .Values.radarr.port }}
  PUID: {{ .Values.PUID }}
  PGID: {{ .Values.PGID }}
  TZ: {{ .Values.timezone }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: {{ .Values.radarr.image }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: radarr-env
        ports:
        - name: webui
          containerPort: {{ .Values.radarr.port }}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: {{ .Values.namespace }}
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "radarr"
spec:
  type: {{ .Values.radarr.service.type }}
  selector:
    app: radarr
  ports:
  - name: webui
    port: {{ .Values.radarr.service.port }}
    targetPort: webui

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.radarr.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.radarr.pvc.size }}
  {{ if .Values.radarr.pvc.useExistingVolume }}
  volumeName: {{ .Values.radarr.pvc.useExistingVolume }}
  {{- end }}

{{ if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: radarr.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  radarr
                port:
                  number: {{ .Values.radarr.service.port }}
{{- end }}