apiVersion: v1
kind: Namespace
metadata:
  name: harness-delegate-ng

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: harness-delegate-ng
  namespace: harness-delegate-ng
spec:
  repo: https://app.harness.io/storage/harness-download/delegate-helm-chart
  chart: harness-delegate-ng
  targetNamespace: harness-delegate-ng
  valuesContent: |-
    delegateName: lab
    accountId: wlgELJ0TTre5aZhzpt8gVA
    delegateToken: {{ k8s.secrets.harness.delegate_token }}
    managerEndpoint: https://app.harness.io/gratis
    delegateDockerImage: harness/delegate:23.11.81601
    replicas: 1
    cpu: 100m
    custom_envs:
      - name: DELEGATE_TASK_CAPACITY
        value: "1"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lab-hpa
  namespace: harness-delegate-ng
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab
  minReplicas: 1
  maxReplicas: 15
  metrics:
  - type: Pods
    pods:
      metric:
        name: io_harness_custom_metric_tasks_currently_executing
      target:
        type: Value
        averageValue: 0.50
  
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: lab-metrics
  namespace: harness-delegate-ng
spec:
  selector:
    matchLabels:
      harness.io/name: lab
  podMetricsEndpoints:
  - port: api
    path: /api/metrics
