apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system

---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ s3.k8s.longhorn.access_key | b64encode }}
  AWS_SECRET_ACCESS_KEY: {{ s3.k8s.longhorn.secret_key | b64encode }}
  AWS_ENDPOINTS: {{ s3.host | b64encode }}

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  targetNamespace: longhorn-system
  valuesContent: |-
    service:
      ui:
        type: LoadBalancer
    persistence:
      reclaimPolicy: Retain
    defaultSettings:
      backupTarget: s3://k8s@us-east-1/longhorn/backups
      backupTargetCredentialSecret: minio

---
apiVersion: v1
data:
  auth: {{ nginx_ingress_auth_secret }}
kind: Secret
metadata:
  name: basic-auth
  namespace: longhorn-system
type: Opaque

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  ingressClassName: nginx
  rules:
    - host: longhorn.k8s.rileysnyder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  longhorn-frontend
                port:
                  number: 80