---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: keys
type: Opaque
data:
  username: keys
  password: {{ k8s.secrets.kkeys.postgres.password | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: pushover
  namespace: reddit-alerts
type: Opaque
data:
  app: {{ k8s.secrets.reddit_alerts.pushover.app | b64encode }}
  user: {{ k8s.secrets.reddit_alerts.pushover.user | b64encode }}