---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: keys
type: Opaque
data:
  username: keys
  password: {{ k8s.secrets.kkeys.postgres.password | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: pushover
  namespace: reddit-alerts
type: Opaque
data:
  app: {{ k8s.secrets.reddit_alerts.pushover.app | b64encode }}
  user: {{ k8s.secrets.reddit_alerts.pushover.user | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: discord-bot
  namespace: discord-bot
type: Opaque
data:
  token: {{ k8s.secrets.discord_bot.token | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: apex-aethir-discord-bot
  namespace: discord-bot
type: Opaque
data:
  token: {{ k8s.secrets.discord_bot.apex_aethir | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-manager
  namespace: discord-bot-manager
type: Opaque
data:
  pgpassword: {{ k8s.secrets.discord_bot_manager.pgpassword | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: google-sheets-service-account
  namespace: python-functions
type: Opaque
data:
  creds: {{ k8s.secrets.python_functions.google_sheets_service_account_json }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-token
  namespace: dnd-generator
data:
  .dockerconfigjson: {{ k8s.secrets.ghcr_docker_config }}
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: dnd-generator
type: Opaque
data:
  PG_PASSWORD: {{ k8s.secrets.dnd_generator.PG_PASSWORD | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: counter
type: Opaque
data:
  PG_PASSWORD: {{ k8s.secrets.counter.PG_PASSWORD | b64encode }}