app: <+service.name.toLowerCase().replace("_", "-").replace(" ", "-")>
image: <+artifact.image>
namespace: <+infra.namespace>

ingress:
  enabled: true
  domain: <+service.name.toLowerCase().replace("_", "-").replace(" ", "-")>.k8s.rileysnyder.dev

service: 
  type: LoadBalancer
  port: 80

pvc:
  enable: true
  size: 25Gi

sa:
  cluster_admin: false