---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hardwareswap-env
  namespace: reddit-alerts
  labels:
    app: hardwareswap
data:
  SUBREDDIT: "hardwareswap"
  DB: "/db/hardwareswap.json"
  POST_TEXT: "dualup;Terramaster"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardwareswap
  namespace: reddit-alerts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hardwareswap
  template:
    metadata:
      labels:
        app: hardwareswap
    spec:
      containers:
      - name: hardwareswap
        image: ghcr.io/rssnyder/discord-reddit-posts:0.0.1-beta.4
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: hardwareswap-env
        env:
        - name: PUSHOVER_APP
          valueFrom:
            secretKeyRef:
              name: pushover
              key: app
        - name: PUSHOVER_USER
          valueFrom:
            secretKeyRef:
              name: pushover
              key: user
        volumeMounts:
        - name: db
          mountPath: /db
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: reddit-alerts
