apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  namespace: frigate
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  hostPath:
    path: /mnt/bulk/k8s/frigate/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: frigate
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: media