image:
  tag: 0.13.1
fullnameOverride: frigate
service:
  type: LoadBalancer
  port: 80
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "frigate"
    external-dns.alpha.kubernetes.io/hostname: frigate.r.ss
config: |
  mqtt:
    host: "mosquitto.mosquitto"
    port: 1883
  database: 
    path: /media/frigate.db
  detectors:
    coral:
      type: edgetpu
      device: usb
  go2rtc:
    streams:
      back: 
        - "ffmpeg:http://192.168.0.97/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>#video=copy#audio=copy#audio=opus"
      back_sub: 
        - "ffmpeg:http://192.168.0.97/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>"
      roam: 
        - "ffmpeg:http://192.168.0.96/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>#video=copy#audio=copy#audio=opus"
      roam_sub: 
        - "ffmpeg:http://192.168.0.96/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>"
  cameras:
    back:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/back?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      detect:
        width: 2560
        height: 1920
      record:
        enabled: true
        events:
          required_zones:
          - sidewalkcorner
          - sidewalk
          - door
      snapshots:
        required_zones:
          - sidewalkcorner
          - sidewalk
          - door
      zones:
        sidewalkcorner:
          coordinates: 1079,797,1087,858,1280,875,1289,659,1176,668
          objects:
            - person
        sidewalk:
          coordinates: 0,764,716,747,716,877,0,961
          objects:
            - person
        door:
          coordinates: 1579,680,1563,902,1631,918,1668,872,1672,682
          objects:
            - person
            - dog
        car:
          coordinates: 617,1920,1419,1920,1634,1920,2027,1920,2127,638,1286,641,1268,847,402,932,0,965,0,1920
          objects:
          - car
      objects:
        track:
          - person
          - dog
          - car
    louie:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.98:554/h264Preview_01_main
      record:
        enabled: false
      detect:
        enabled: false
    front:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.99:554/h264Preview_01_main
            roles:
              - detect
      detect:
        width: 2560
        height: 1440
      objects:
        mask:
          - 2048,922,2087,1217,1984,1440,1737,1440,1656,1187,1680,950,1901,619
      motion:
        mask:
          - 2048,922,2087,1217,1984,1440,1737,1440,1656,1187,1680,950,1901,619
      record:
        enabled: true
    # roam:
    #   ffmpeg:
    #     inputs:
    #     - path: rtsp://127.0.0.1:8554/roam?video=copy&audio=aac
    #       input_args: preset-rtsp-restream
    #       roles:
    #         - record
    #     - path: rtsp://127.0.0.1:8554/roam_sub?video=copy
    #       input_args: preset-rtsp-restream
    #       roles:
    #         - detect
    #   detect:
    #     width: 2560
    #     height: 1920
    #   record:
    #     enabled: true
    # garage:
    #   ffmpeg:
    #     inputs:
    #       - path: rtsp://wyze-bridge:8554/garage-door
    #         roles:
    #           - detect
    #   record:
    #     enabled: true
    # amcrest1:
    #   ffmpeg:
    #     inputs:
    #       - path: rtsp://admin:admin@192.168.0.119:554/cam/realmonitor?channel=1&subtype=0
    #   record:
    #     enabled: false
    #   detect:
    #     enabled: false
    lab:
      ffmpeg:
        inputs:
          - path: rtsp://admin:admin@192.168.0.120:554/cam/realmonitor?channel=1&subtype=0
      record:
        enabled: false
      detect:
        enabled: false
      motion:
        mask:
          - 2320,125,2199,872,1828,991,1914,53
      objects:
        mask:
          - 2320,125,2199,872,1828,991,1914,53
  snapshots:
    enabled: True
    timestamp: True
    retain:
      default: 30
      objects:
        person: 30
persistence:
  media:
    enabled: True
    existingClaim: media
nodeSelector:
  kubernetes.io/hostname: charlie
coral:
  enabled: true
  hostPath: /dev/bus/usb
resources:
  requests:
    cpu: 1500m
    memory: 2Gi