---
apiVersion: v1
kind: Namespace
metadata:
  name: frigate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zfs-frigate
  namespace: frigate
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/pale/frigate"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zfs-frigate
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: zfs-frigate
  storageClassName: manual