apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-frigate
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.11
    path: "/bucket/frigate"
  mountOptions:
    - nfsvers=4.2