apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: gitness
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: dind-vol
            mountPath: /var/run
          - name: gitness-vol
            mountPath: /data
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-vol
            mountPath: /var/run
      volumes:
        - name: dind-vol
          emptyDir:
        - name: gitness-vol
          persistentVolumeClaim:
            claimName: gitness-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
  - name: web
    port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi