apiVersion: v1
kind: Namespace
metadata:
  name: gitness

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitness
  namespace: gitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitness
  template:
    metadata:
      labels:
        app: gitness
    spec:
      containers:
      - name: gitness
        image: harness/gitness
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: dind-vol
            mountPath: /var/run
          - name: gitness-vol
            mountPath: /data
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-vol
            mountPath: /var/run
      volumes:
        - name: dind-vol
          emptyDir:
        - name: gitness-vol
          persistentVolumeClaim:
            claimName: gitness-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: gitness
  namespace: gitness
spec:
  type: NodePort
  selector:
    app: gitness
  ports:
  - name: web
    port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitness-pvc
  namespace: gitness
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi