apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: twofivefour
  namespace: metallb-system
spec:
  addresses:
  - 192.168.254.1-192.168.254.254

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisethis
  namespace: metallb-system
spec:
  ipAddressPools:
  - twofivefour