---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: isengard-runner
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: rssnyder/isengard
