---
version: "3"
services:

  # minio:
  #   image: quay.io/minio/minio
  #   network_mode: host
  #   restart: unless-stopped
  #   volumes:
  #     - /home/riley/appdata/minio:/data
  #   environment:
  #     MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
  #     MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
  #   command: server /data --console-address ":9001"

  grafana:
    image: grafana-custom
    container_name: grafana
    ports:
      - 3000:3000
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /home/riley/appdata/grafana:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: "https://metrics.rileysnyder.org"
      GF_AUTH_GOOGLE_ENABLED: "true"
      GF_AUTH_GOOGLE_CLIENT_ID: "${GF_AUTH_GOOGLE_CLIENT_ID}"
      GF_AUTH_GOOGLE_CLIENT_SECRET: "${GF_AUTH_GOOGLE_CLIENT_SECRET}"
      GF_AUTH_GOOGLE_SCOPES: "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
      GF_AUTH_GOOGLE_AUTH_URL: "https://accounts.google.com/o/oauth2/auth"
      GF_AUTH_GOOGLE_TOKEN_URL: "https://accounts.google.com/o/oauth2/token"
      GF_AUTH_GOOGLE_ALLOWED_DOMAINS: "rileysnyder.org gmail.com"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /home/riley/appdata/prometheus:/etc/prometheus
      - /home/riley/appdata/prometheus-data:/prometheus
    ports:
      - 9090:9090
    network_mode: "host"
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  pushgateway:
    image: prom/pushgateway
    restart: always
    container_name: pushgateway
    ports:
      - 9092:9091

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - /home/riley/appdata/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    network_mode: "host"

  files:
    image: svenstaro/miniserve
    restart: always
    container_name: files
    volumes:
      - /mnt/freezer/media:/tmp
    ports:
      - 8080:8080
    network_mode: "host"
    command: /tmp
    
  plex_exporter:
    build: "/home/riley/appdata/plex_exporter"
    restart: always
    container_name: "plex_exporter"
    ports:
      - 9594:9594
    volumes:
      - /home/riley/appdata/plex_exporter/config.json:/config.json
    command: -config /config.json

  # promcord:
  #   image: "promcord:local"
  #   restart: always
  #   container_name: "promcord"
  #   ports:
  #     - 8787:8080
  #   environment:
  #     DISCORD_TOKEN: "${PROMCORD_DISCORD_TOKEN}"
  #   volumes:
  #     - /home/riley/appdata/grafana:/var/lib/grafana

  digitalocean_exporter:
    image: metalmatze/digitalocean_exporter:0.6.1
    container_name: digitalocean_exporter
    environment:
      DIGITALOCEAN_TOKEN: "${DIGITALOCEAN_TOKEN}"
    restart: always
    ports:
    - "8789:9212"

  # minecraft:
  #   image: crbanman/papermc-lazymc
  #   restart: always
  #   container_name: minecraft
  #   ports:
  #     - 25565:25565
  #   network_mode: "host"
  #   environment:
  #     MC_VERSION: "latest"
  #     MC_RAM: "4G"
  #   volumes:
  #     - /home/riley/appdata/minecraft:/papermc

  omada:
    container_name: omada
    image: mbentley/omada-controller:5.3
    environment:
      MANAGE_HTTP_PORT: 8088
      MANAGE_HTTPS_PORT: 8043
      PORTAL_HTTP_PORT: 8088
      PORTAL_HTTPS_PORT: 8843
      SHOW_SERVER_LOGS: "true"
      SHOW_MONGODB_LOGS: "false"
      TZ: 'America/Chicago'
    volumes:
      - /home/riley/appdata/omada/data:/opt/tplink/EAPController/data
      - /home/riley/appdata/omada/work:/opt/tplink/EAPController/work
      - /home/riley/appdata/omada/logs:/opt/tplink/EAPController/logs    
    network_mode: host
    restart: unless-stopped
  
  # omada_exporter:
  #   image: ghcr.io/charlie-haley/omada_exporter:0.5.0
  #   container_name: "omada_exporter"
  #   restart: unless-stopped
  #   ports:
  #     - 9202:9202
  #   environment:
  #     OMADA_HOST: "https://192.168.0.11:8043"
  #     OMADA_USER: "docker"
  #     OMADA_PASS: "${OMADA_PASS}"
  #     OMADA_SITE: "Default"
  #     OMADA_INSECURE: "true"

  ispy:
    container_name: ispy
    image: doitandbedone/ispyagentdvr
    environment:
      TZ: 'America/Chicago'
    volumes:
      - /home/riley/appdata/ispyagentdvr/config:/agent/Media/XML/
      - /mnt/trash/cams:/agent/Media/WebServerRoot/Media/
      - /home/riley/appdata/ispyagentdvr/commands:/agent/Commands/
    network_mode: host
    restart: unless-stopped

  #homeassistant:
  #  container_name: homeassistant
  #  image: "ghcr.io/home-assistant/home-assistant:stable"
  #  volumes:
  #    - /home/riley/appdata/homeassistant:/config
  #    - /etc/localtime:/etc/localtime:ro
  #  environment:
  #    - TZ='America/Chicago'
  #  restart: unless-stopped
  #  privileged: "true"
  #  network_mode: host

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - /home/riley/appdata/syncthing:/config
      - /mnt/trash/backup/syncthing:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  signal:
    image: bbernhard/signal-cli-rest-api
    container_name: signal
    environment:
      MODE: native
      AUTO_RECEIVE_SCHEDULE: "0 8 * * *"
    volumes:
      - /home/riley/appdata/signal:/home/.local/share/signal-cli
    ports:
      - 8989:8080
