---
version: "3"
services:

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    environment:
      PUID: 65534
      PGID: 1001
      VERSION: docker
    ports:
      - "32400:32400"
    volumes:
      - $APPDATA/plex:/config
      - /bucket/media:/media
      - /mnt/fake:/mnt/fake

  qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrentvpn
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /mnt/fake/downloads:/downloads
      - /bucket/media/movies:/movies
      - /bucket/media/tv:/tv
      - /bucket/media/syndicated:/syndicated
      - /bucket/media/books:/books
      - $APPDATA/qbittorrentvpn:/config
      - /etc/localtime:/etc/localtime:ro
      - $APPDATA/VueTorrent:/VueTorrent
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "7001:7001"
      - "8118:8118"
    environment:
      VPN_ENABLED: yes
      VPN_USER: "${VPN_USER}"
      VPN_PASS: "${VPN_PASS}"
      VPN_PROV: pia
      VPN_CLIENT: wireguard
      STRICT_PORT_FORWARD: yes
      ENABLE_PRIVOXY: yes
      LAN_NETWORK: "192.168.0.0/24"
      NAME_SERVERS: "209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1"
      WEBUI_PORT: 7001
      UMASK: 000
      PUID: 65534
      PGID: 1001

  qbt_exporter:
    image: esanchezm/prometheus-qbittorrent-exporter
    container_name: qbt_exporter
    restart: unless-stopped
    ports:
      - "8119:8119"
    environment:
      QBITTORRENT_HOST: "192.168.0.11"
      QBITTORRENT_PORT: 7001
      EXPORTER_PORT: 8119
      QBITTORRENT_USER: admin
      QBITTORRENT_PASS: "${QBITTORRENT_PASS}"
      VERIFY_WEBUI_CERTIFICATE: false

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      PUID: 65534
      PGID: 1001
      TZ: America/Chicago
    volumes:
      - $APPDATA/sonarr:/config
      - /bucket/media/tv:/tv
      - /mnt/fake/downloads:/downloads
    ports:
      - 7002:8989

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: 65534
      PGID: 1001
      TZ: America/Chicago
    volumes:
      - $APPDATA/radarr:/config
      - /bucket/media/movies:/movies
      - /mnt/fake/downloads:/downloads
    ports:
      - 7003:7878

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      PUID: 65534
      PGID: 1001
      TZ: America/Chicago
    volumes:
      - $APPDATA/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      PUID: 65534
      PGID: 1001
      TZ: America/Chicago
      VPN_ENABLED: no
    volumes:
      - $APPDATA/deluge:/config
      - /bucket/media/books:/downloads
    ports:
      - "8112:8112"
      - "8117:8118"
      - "58846:58846"
      - "58946:58946"
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - $APPDATA/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - $APPDATA/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  files:
    image: svenstaro/miniserve
    container_name: files
    restart: always
    volumes:
      - /bucket/media:/tmp
    ports:
      - 8080:8080
    command: /tmp

  send:
    image: registry.gitlab.com/timvisee/send:latest
    restart: always
    ports:
      - '8383:8383'
    volumes:
      - /mnt/fake/send:/uploads
    environment:
      - DHPARAM_GENERATION=false
      - NODE_ENV=production
      - DETECT_BASE_URL=true
      - PORT=8383
      - REDIS_HOST=redis
      - FILE_DIR=/uploads
      - MAX_FILE_SIZE=21474836480

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - send-redis:/data

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - $APPDATA/syncthing:/config
      - /bucket/backup/syncthing:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - $APPDATA/pigallery2:/app/data/config
      - pigallery2:/app/data/db
      - /bucket/backup/syncthing/phone-camera:/app/data/images/camera:ro
      - /bucket/backup/syncthing/phone-pictures:/app/data/images/pictures:ro
      - /bucket/photos:/app/data/images/old:ro
    ports:
      - 8345:80
    restart: always
  
  # ispy:
  #   container_name: ispy
  #   image: doitandbedone/ispyagentdvr
  #   environment:
  #     TZ: 'America/Chicago'
  #   volumes:
  #     - $APPDATA/ispyagentdvr/config:/agent/Media/XML/
  #     - /mnt/trash/cams:/agent/Media/WebServerRoot/Media/
  #     - $APPDATA/ispyagentdvr/commands:/agent/Commands/
  #   network_mode: host
  #   restart: unless-stopped

volumes:
  send-redis:
  pigallery2:
