---
version: "3"
services:

  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      - 8475:8475 # qbt
    volumes:
      - $APPDATA/gluetun:/gluetun
    environment:
      VPN_SERVICE_PROVIDER: private internet access
      VPN_TYPE: openvpn
      OPENVPN_USER: "${VPN_USER}"
      OPENVPN_PASSWORD: "${VPN_PASS}"
      SERVER_REGIONS: Netherlands

  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    environment:
      PUID: 65534
      PGID: 1001
      VERSION: docker
    ports:
      - "32400:32400"
    volumes:
      - $APPDATA/plex:/config
      - /bucket/media:/media
      - /mnt/fake:/mnt/fake

  qbt:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbt
    network_mode: "service:gluetun"
    environment:
      PUID: 65534
      PGID: 1001
      TZ: America/Chicago
      WEBUI_PORT: 8475
    volumes:
      - $APPDATA/qbt:/config
      - /mnt/fake/downloads:/downloads
      - /bucket/media/movies:/movies
      - /bucket/media/tv:/tv
      - /bucket/media/syndicated:/syndicated
      - /bucket/media/books:/books
      - /bucket/media/music:/music
    restart: unless-stopped

  qbt_exporter:
    image: esanchezm/prometheus-qbittorrent-exporter
    container_name: qbt_exporter
    restart: unless-stopped
    ports:
      - "8119:8119"
    environment:
      QBITTORRENT_HOST: "192.168.0.6"
      QBITTORRENT_PORT: 8475
      EXPORTER_PORT: 8119
      QBITTORRENT_USER: admin
      QBITTORRENT_PASS: "${QBITTORRENT_PASS}"
      VERIFY_WEBUI_CERTIFICATE: "false"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      PUID: 65534
      PGID: 1001
      TZ: America/Chicago
    volumes:
      - $APPDATA/sonarr:/config
      - /bucket/media/tv:/tv
      - /mnt/fake/downloads:/downloads
    ports:
      - 7002:8989

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: 65534
      PGID: 1001
      TZ: America/Chicago
    volumes:
      - $APPDATA/radarr:/config
      - /bucket/media/movies:/movies
      - /mnt/fake/downloads:/downloads
    ports:
      - 7003:7878

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      PUID: 65534
      PGID: 1001
      TZ: America/Chicago
    volumes:
      - $APPDATA/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - $APPDATA/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - $APPDATA/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  tautulli-exporter:
    image: nwalke/tautulli_exporter
    container_name: tautulli-exporter
    environment:
      TAUTULLI_API_KEY: "${TAUTULLI_KEY}"
      TAUTULLI_URI: http://192.168.0.6:8181
    volumes:
      - $APPDATA/tautulli:/config
    ports:
      - 9487:9487
    restart: unless-stopped

  files:
    image: svenstaro/miniserve
    container_name: files
    restart: always
    volumes:
      - /bucket/media:/tmp/media
      - /mnt/fake/downloads:/tmp/downloads
    ports:
      - 8080:8080
    command: /tmp

  send:
    image: registry.gitlab.com/timvisee/send:latest
    restart: always
    user: "0"
    ports:
      - '8383:8383'
    volumes:
      - send:/uploads
    environment:
      - DHPARAM_GENERATION=false
      - NODE_ENV=production
      - DETECT_BASE_URL=true
      - PORT=8383
      - REDIS_HOST=redis
      - FILE_DIR=/uploads
      - MAX_FILE_SIZE=21474836480

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - send-redis:/data

  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - $APPDATA/syncthing:/config
      - /bucket/backup/syncthing:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_USER: "admin"
      PHOTOPRISM_ADMIN_PASSWORD: "${QBITTORRENT_PASS}"
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "https://photos.rileysnyder.org/"
      PHOTOPRISM_ORIGINALS_LIMIT: 500000
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: 85
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "${QBITTORRENT_PASS}"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
    working_dir: "/photoprism"
    volumes:
      - "/bucket/prism:/photoprism/originals"
      # - "/bucket/photos:/photoprism/import"
      - "/bucket/backup/syncthing/phone-pictures:/photoprism/import/pictures"
      - "/bucket/backup/syncthing/phone-camera:/photoprism/import/camera"
      - "$APPDATA/photoprism:/photoprism/storage"

  ofelia:
    restart: unless-stopped
    image: mcuadros/ofelia:latest
    container_name: ofelia
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$APPDATA/photoprism/photoprism.ini:/etc/ofelia/config.ini"

  mariadb:
    restart: unless-stopped
    image: mariadb:10.10
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "$APPDATA/photoprism-db:/var/lib/mysql"
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "${QBITTORRENT_PASS}"
      MARIADB_ROOT_PASSWORD: "${QBITTORRENT_PASS}"

  discord-minecraft-server-stats:
    image: ghcr.io/rssnyder/discord-minecraft-server-stats:0.0.3
    environment:
      TOKEN: "${MINECRAFT_DISCORD_TOKEN}"
      DOMAIN: yourearat.com
      STATUS: 0
      LOOP: 15
      USERS: 5

volumes:
  send-redis:
  send:
  pigallery2:
  torch:
  huggingface:
