apiVersion: v1
kind: Namespace
metadata:
  name: mosquitto

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: mosquitto
  labels:
    app: config
data:
  mosquitto.conf: |
    allow_anonymous false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        imagePullPolicy: IfNotPresent
        env:
        - name: ALLOW_UNSECURED_MODE
          value: "true"
        ports:
        - name: mqtt
          containerPort: 1883
        - name: other
          containerPort: 9001
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: config
        configMap:
          name: config

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mosquitto.r.ss
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    port: 1883
    targetPort: mqtt
