apiVersion: v1
kind: Namespace
metadata:
  name: files

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: files
  namespace: files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: files
  template:
    metadata:
      labels:
        app: files
    spec:
      nodeName: charlie
      containers:
      - name: miniserve
        image: svenstaro/miniserve
        imagePullPolicy: IfNotPresent
        env:
        - name: MINISERVE_PATH
          value: /tmp
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        hostPath:
          path: /mnt/bulk/k8s/files

---
apiVersion: v1
kind: Service
metadata:
  name: files
  namespace: files
spec:
  type: LoadBalancer
  selector:
    app: files
  ports:
  - name: http
    port: 80
    targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: files
  namespace: files
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "files"
    external-dns.alpha.kubernetes.io/hostname: files.r.ss
spec:
  ingressClassName: nginx
  rules:
    - host: files.k8s.rileysnyder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  files
                port:
                  number: 80
