apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnd-generator-api
  namespace: pg2s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnd-generator-api
  template:
    metadata:
      labels:
        app: dnd-generator-api
    spec:
      containers:
      - name: pg2s3
        image: rssnyder/pg2s3
        imagePullPolicy: Always
        args:
        - "-conf"
        - "/pg2s3/pg2s3.conf"
        volumeMounts:
        - name: config
          mountPath: "/pg2s3"
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: dnd-generator-api