apiVersion: apps/v1
kind: Deployment
metadata:
  name: dst
  namespace: pg2s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dst
  template:
    metadata:
      labels:
        app: dst
    spec:
      containers:
      - name: pg2s3
        image: rssnyder/pg2s3
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: "/pg2s3"
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: dst