apiVersion: v1
kind: Namespace
metadata:
  name: reddit-alerts

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reddit-alerts
  namespace: reddit-alerts
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 500M