---
- name: Backup kate
  hosts: kate
  become: yes

  tasks:

    - name: backup media
      ignore_errors: yes
      shell:
        cmd: rclone -P copy /mnt/freezer/media crypt:media
    
    - name: delete downloads
      ignore_errors: yes
      shell:
        cmd: rclone -P purge crypt:media/downloads
        
    # - name: backup util
    #   ignore_errors: yes
    #   shell:
    #     cmd: rclone sync /mnt/freezer/util/ crypt:util/

    - name: backup riley
      ignore_errors: yes
      shell:
        cmd: rclone -P copy /home/riley crypt:kate/home/riley
    
    - name: backup plex
      ignore_errors: yes
      shell:
        cmd: rclone -P copy /home/plex crypt:kate/home/plex

    - name: download photos
      ignore_errors: yes
      shell:
        cmd: "rclone -P copy photos: /home/riley/backup/Photos/google/"
