---
- name: Backup data
  hosts: kate
  gather_facts: yes
  become: yes

  tasks:

    - name: backup media
      shell:
        cmd: rclone -P sync /mnt/freezer/media crypt:media

    - name: backup users
      shell:
        cmd: "rclone -P sync /home/{{ item }} crypt:{{ item }}"
      loop:
        - riley
        - infra
