---
- name: Backup kate
  hosts: kate
  become: yes

  tasks:

    - name: backup media
      shell:
        cmd: rclone -P sync /mnt/freezer/media crypt:media

    - name: backup users
      shell:
        cmd: "rclone -P sync /home/{{ item }} crypt:kate-{{ item }}"
      loop:
        - riley
        - infra
