---
- name: Backup kate
  hosts: kate
  become: yes

  tasks:

    - name: backup media
      ignore_errors: yes
      shell:
        cmd: rclone -P sync /mnt/freezer/media crypt:media
        
    - name: backup util
      ignore_errors: yes
      shell:
        cmd: rclone sync /mnt/freezer/util/ crypt:util/

    - name: backup users
      ignore_errors: yes
      shell:
        cmd: rclone -P copy /home crypt:kate/home
