---
- name: Backup kate
  hosts: kate
  become: yes

  tasks:

    - name: backup media
      ignore_errors: yes
      shell:
        cmd: rclone -P sync /mnt/freezer/media crypt:media
        
    - name: backup minio
      ignore_errors: yes
      shell:
        cmd: rclone -P copy /home/infra/appdata/minio crypt:minio
        
#     - name: backup util
#       ignore_errors: yes
#       shell:
#         cmd: rclone -P sync /mnt/freezer/util crypt:util

    - name: backup users
      ignore_errors: yes
      shell:
        cmd: rclone -P copy /home crypt:kate/home
