---
- name: Backup data
  hosts: kate
  gather_facts: yes
  become: yes

  tasks:

    - name: backup media
      shell:
        cmd: rclone -P sync /mnt/freezer/media crypt:media

    - name: backup riley
      shell:
        cmd: rclone -P sync /home/riley crypto:riley
