---
- name: Backup kate
  hosts: kate
  become: no

  tasks:

    # - name: backup media
    #   ignore_errors: yes
    #   shell:
    #     cmd: rclone -P copy /mnt/freezer/media crypt:media
    
    # - name: delete downloads
    #   ignore_errors: yes
    #   shell:
    #     cmd: rclone -P purge crypt:media/downloads
        
    # - name: backup util
    #   ignore_errors: yes
    #   shell:
    #     cmd: rclone sync /mnt/freezer/util/ crypt:util/

    - name: backup riley
      shell:
        chdir: /home/riley
        cmd: |
          docker-compose down; tar -czvf /mnt/trash/backup/riley.$(date +%m.%d.%y).tar.gz /home/riley; docker-compose up -d
    
    - name: backup plex
      shell:
        chdir: /home/plex
        cmd: |
          docker-compose down; tar -czvf /mnt/trash/backup/plex.$(date +%m.%d.%y).tar.gz /home/plex; docker-compose up -d
      become: yes
    become_user: plex

    - name: download photos
      ignore_errors: yes
      shell:
        cmd: "rclone -P copy photos: /mnt/trash/backup/Photos/google/"
