---
- name: Backup kate
  hosts: kate
  become: yes

  tasks:

    # - name: backup riley
    #   shell:
    #    chdir: /home/riley
    #    cmd: tar -czvf /bucket/backup/kate_riley.$(date +%m.%y).tar.gz /home/riley

    # - name: backup plex
    #   shell:
    #     chdir: /home/plex
    #     cmd: docker-compose down && tar -czvf /bucket/backup/users/kate_plex.$(date +%m.%d.%y).tar.gz /home/plex; docker-compose up -d
    #   become: yes

    # - name: download photos
    #   shell:
    #     cmd: |
    #       rclone -P copy photos: /bucket/backup/Photos/google/

    - name: sync
      shell:
        cmd: |
          rclone sync /bucket/backup crypt:archive/backup
    
    - name: copy
      shell:
        cmd: |
          rclone -vP copy /bucket/media/books/ crypt:media/books/
          rclone -vP copy /bucket/frigate/     crypt:frigate/