---
- name: Backup kate
  hosts: kate
  become: yes

  tasks:

    # - name: backup plex
    #   shell:
    #     chdir: /home/plex
    #     cmd: docker-compose down && tar -czvf /bucket/backup/users/kate_plex.$(date +%m.%d.%y).tar.gz /home/plex; docker-compose up -d
    #   become: yes

    - name: sync
      shell:
        cmd: |
          rclone sync /bucket/backup crypt:archive/backup
          rsync -ar --delete /bucket/backup charlie:/pale/bucket/
          rsync -ar --delete /bucket/media/syndicated charlie:/pale/bucket/
    
    - name: copy
      shell:
        cmd: |
          rclone -vP copy /bucket/media/books/ crypt:media/books/
          rclone -vP copy /bucket/photos       crypt:photos
