---
- hosts: hurley,oca0
  become: yes
  roles:
    - role: caddy_ansible.caddy_ansible
      caddy_setcap: true
      caddy_systemd_capabilities_enabled: true
      caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
      caddy_packages:
      - github.com/caddy-dns/digitalocean@master
      caddy_config: "{{ lookup('template', 'templates/' + ansible_hostname + '/Caddyfile.j2') }}"
