---
- name: clean
  hosts: all
  become: yes

  tasks:

    - name: clean
      shell:
        cmd: |
          sudo systemctl stop snapd
          sudo apt remove --purge --assume-yes snapd
          rm -rf ~/snap/
          sudo rm -rf /var/cache/snapd/ 