---
- name: Discord bot for DeFiDope#5264 927173835541872660
  hosts: oca1
  become: yes

  tasks:

    - name: set service info
      set_fact:
        app_name: discord-d2-finance-marketcap
        version: 0.0.1-beta.1
        service_name: "defidope-discord-d2-finance-marketcap"
        service_binary: "discord-d2-finance-marketcap"
        service_desc: "defidope-discord-d2-finance-marketcap"
        service_opts: "-token '{{ defidope_d2_token }}' -refresh 60 -activity 'Marketcap'"
        service_type: simple

    - name: create service dir
      file: 
        state: directory
        path: "/etc/{{ app_name }}"
        owner: root
        group: root

    - name: download source
      get_url:
        url: "https://github.com/rssnyder/{{ app_name }}/releases/download/v{{ version }}/{{ app_name }}_{{ version }}_linux_{{ arch }}.tar.gz"
        dest: "/etc/{{ app_name }}/{{ app_name }}.tar.gz"
        mode: '0700'
    
    - name: extract
      unarchive:
        remote_src: yes
        src: "/etc/{{ app_name }}/{{ app_name }}.tar.gz"
        dest: "/etc/{{ app_name }}/"
    
    - name: move
      copy:
        remote_src: yes
        src: "/etc/{{ app_name }}/{{ app_name }}"
        dest: "/etc/{{ app_name }}/{{ service_name }}"
        mode: '0700'
    
    - name: copy service file
      template: 
        src: templates/service.j2
        dest: "/etc/systemd/system/{{ service_name }}.service"
    
    - name: reload
      shell:
        cmd: systemctl daemon-reload

    - name: start
      systemd:
        state: restarted
        name: "{{ service_name }}"
        enabled: yes
