---
- name: Install discord-stock-ticker
  hosts: all
  become: yes

  tasks:

    - name: install pip3
      package:
        name: python3-pip
        state: latest
        update_cache: yes

    - name: Install boto3
      pip:
        name: boto3

    - name: create dst dir
      file: 
        state: directory
        path: /etc/discord-stock-ticker
        owner: root
        group: root

    - name: Download dst
      get_url:
        url: "https://github.com/rssnyder/discord-stock-ticker/releases/download/{{ ticker_version }}/discord-stock-ticker-{{ ticker_version }}-{{ arch }}.tar.gz"
        dest: /etc/discord-stock-ticker/discord-stock-ticker.tar.gz
        mode: '0700'

    - name: Extract dst
      unarchive:
        remote_src: yes
        src: /etc/discord-stock-ticker/discord-stock-ticker.tar.gz
        dest: /etc/discord-stock-ticker/
    
    - name: copy service config
      template: 
        src: dst.service.j2
        dest: "/etc/systemd/system/{{ item.value.name }}.service"
      loop: "{{ clients | dict2items }}"
  
    - name: reload
      shell:
        cmd: systemctl daemon-reload
      
    - name: Start dst
      systemd:
        state: restarted
        name: "{{ item.value.name }}.service"
      loop: "{{ clients | dict2items }}"
