---
- name: Backup discord-stock-ticker
  hosts: oracle_dst,oracle_arm_dst
  become: yes

  tasks:

    - name: install pip3
      package:
        name: python3-pip
        state: latest
        update_cache: yes
      when: clients

    - name: Install boto3
      pip:
        name: boto3
      when: clients

    - name: Backup DB
      amazon.aws.aws_s3:
        s3_url: "{{ s3.host }}"
        aws_access_key: "{{ s3.username }}"
        aws_secret_key: "{{ s3.password }}"
        encrypt: no
        bucket: ocb0
        object: "dst/database/{{ item.value.name }}.state"
        src: "/etc/discord-stock-ticker/{{ item.value.name }}.state"
        mode: put
        permission: []
      loop: "{{ clients | dict2items }}"
