---
- name: Backup discord-stock-ticker
  hosts: oca0
  become: yes

  tasks:

    - name: install pip3
      package:
        name: python3-pip
        state: latest
        update_cache: yes
      when: clients

    - name: Install boto3
      pip:
        name: boto3
      when: clients
    
    - name: Install cryptography
      pip:
        name: cryptography
      when: clients

    - name: Backup DB
      amazon.aws.aws_s3:
        s3_url: "{{ s3.host }}"
        region: us-east-1
        aws_access_key: "{{ s3.access_key }}"
        aws_secret_key: "{{ s3.secret_key }}"
        encrypt: no
        bucket: discord-stock-ticker
        object: "database/{{ item.key }}.state"
        src: "/etc/discord-stock-ticker/{{ item.key }}.state"
        mode: put
        permission: []
      loop: "{{ clients | dict2items }}"
