---
- name: Docker config
  hosts: hurley
  become: no

  tasks:
    
    - name: copy service file
      copy: 
        src: templates/hurley_docker-compose.yml
        dest: /home/riley/docker-compose.yml
    
    - name: reload
      shell:
        cmd: docker compose up -d --remove-orphans
        chdir: /home/riley

