---
- name: Docker config
  hosts: hurley
  become: no
  tasks:

    - name: Install Python and python3-pip
      package:
        name:
          - python3
          - python3-pip
        state: present 

    - name: Install docker module for Python
      pip:
        name: 
          - docker
          - docker-compose

    - name: copy service file
      copy: 
        src: templates/hurley_docker-compose.yml
        dest: /home/riley/docker-compose.yml

    - name: copy homer file
      template: 
        src: templates/homer.yml
        dest: /home/riley/appdata/homer/config.yml

    - name: copy caddy file
      template: 
        src: templates/Caddyfile
        dest: /home/riley/appdata/Caddyfile
    
    - name: Docker-compose up
      community.docker.docker_compose:
        project_src: /home/riley
