---
- name: configure iptables
  hosts: oracle,oracle_dst
  become: yes

  tasks:

    - name: allow all over tailscale
      ansible.builtin.lineinfile:
        path: /etc/iptables/rules.v4 
        regexp: '^-A INPUT -i tailscale0 -p tcp -m state --state NEW -m tcp -j ACCEPT$'
        line: -A INPUT -i tailscale0 -p tcp -m state --state NEW -m tcp -j ACCEPT
        insertafter: '^-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT$'
    
    - name: restart iptables
      systemd:
        state: restarted
        name: iptables
