---
- name: configure iptables
  hosts: oc
  become: yes

  tasks:

    - name: allow all over tailscale
      ansible.builtin.lineinfile:
        path: /etc/iptables/rules.v4 
        regexp: '^-I INPUT 6 -m state --state NEW -p tcp --dport 9100 -j ACCEPT$'
        line: -I INPUT 6 -m state --state NEW -p tcp --dport 9100 -j ACCEPT
        insertafter: '^-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT$'
    
    - name: restart iptables
      systemd:
        state: restarted
        name: iptables
