---
- name: configure iptables
  hosts: oc
  become: yes

  tasks:

    - name: allow all over tailscale
      ansible.builtin.lineinfile:
        path: /etc/iptables/rules.v4 
        regexp: '^-A INPUT -i tailscale0 -j ACCEPT$'
        line: -A INPUT -i tailscale0 -j ACCEPT
        insertafter: '^-A INPUT -i lo -j ACCEPT$'
    
    - name: restart iptables
      shell:
        cmd: iptables-restore < /etc/iptables/rules.v4
