---
- name: uninstall k3s node
  hosts:
  - oca0
  - oca1
  - oca2
  - oca3
  - oca4
  - oca5
  - oca6
  - oca7
  - oca8
  - oca9
  - oca10
  - oca11
  become: yes
  tasks:
    - shell: systemctl stop tailscaled
    - shell: rm -rf /var/lib/tailscale/*
    - shell: rm /etc/apt/sources.list.d/pkgs_tailscale_com_stable_ubuntu.list
    - shell: rm /etc/apt/sources.list.d/tailscale.list
    # - shell: apt remove tailscale
