---
- name: copy k3s manifests
  hosts: charlie
  become: yes

  tasks:
    
    - template:
        src: "{{ item }}"
        dest: /var/lib/rancher/k3s/server/manifests/{{ item | basename | regex_replace('\.j2$', '') }}
      with_fileglob:
        - ../infra/k8s/k3s/*.yaml
    
    - template:
        src: templates/kubelet.config
        dest: /var/lib/rancher/k3s/kubelet.config
    
    - template:
        src: templates/k3s-cleanup.service
        dest: /etc/systemd/system/k3s-cleanup.service
    
    - name: reload
      shell:
        cmd: systemctl daemon-reload


