---
- name: Generate promethus target config
  hosts: all

  tasks:

    - name: get tailscale ip
      set_fact:
        tailscale_ip={{ hostvars[inventory_hostname]['ansible_tailscale0']['ipv4']['address'] }}
    
    - name: copy targets config
      template: 
        src: targets.yml.j2
        dest: /home/riley/appdata/prometheus.yml
        owner: riley
        group: riley
      when: inventory_hostname == 'hurley'
    
    - name: reload
      uri:
        url: http://192.168.0.3:9090/-/reload
        method: POST
      when: inventory_hostname == 'hurley'
