- hosts: all
  become: yes
  roles:
     - { role: ansible-role-squid }
  tasks:

    - name: allow 3128 over nebula
      ansible.builtin.lineinfile:
        path: /etc/iptables/rules.v4 
        regexp: '^-A INPUT -i nebula1 -p tcp -m state --state NEW -m tcp --dport 3128 -j ACCEPT$'
        line: -A INPUT -i nebula1 -p tcp -m state --state NEW -m tcp --dport 3128 -j ACCEPT
        insertafter: '^-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT$'
    
    - name: restart iptables
      systemd:
        state: restarted
        name: iptables
    
    - name: Allow all access to 3128
      community.general.ufw:
        rule: allow
        port: 3128
