- name: rclone backup on a schedule
  hosts: cornelius
  become: yes

  roles:
  - role: rclone
    vars:
      rclone_opts: "-v copy /bucket/backup crypt:bucket/backup -L"
      rclone_utc_hour: 4

---
- name: rclone backup on a schedule
  hosts: charlie
  become: yes

  roles:
  - role: rclone
    vars:
      rclone_opts: "-v copy /mnt/bulk/k8s/frigate crypt:frigate -L"
      rclone_utc_hour: 6