---
- name: Install redis
  hosts: all
  become: yes

  tasks:

    - name: Allow all access from nebula
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
      loop:
        - 192.168.100.0/24
        - 10.0.0.0/8
    
    - name: Allow all access to 22
      community.general.ufw:
        rule: allow
        port: 22

    - name: Allow everything and enable community.general.ufw
      community.general.ufw:
        state: enabled
        policy: reject
