---
- name: Download youtube videos/music
  hosts: kate

  tasks:

    - name: Install yt-dlp
      pip:
        name: yt-dlp
        extra_args: --user

    - name: Wubbillionaire
      shell:
        cmd: /home/riley/.local/bin/yt-dlp -i --extract-audio --audio-format mp3 --add-metadata --metadata-from-title "%(artist)s - %(title)s" --postprocessor-args "-metadata album=Wubbillionaire -metadata artist='Dennis Richardson'" --download-archive /mnt/freezer/media/music/Wubbillionaire/.log -o '/mnt/freezer/media/music/Wubbillionaire/%(playlist_index)s-%(title)s.%(ext)s' https://www.youtube.com/playlist?list=PL1d05GXUOoNlXXRR8UWHWsY4oTi8Vuf1y
        
    - name: Kidz Bop
      shell:
        cmd: /home/riley/.local/bin/yt-dlp -i --extract-audio --audio-format mp3 --add-metadata --metadata-from-title "%(artist)s - %(title)s" --postprocessor-args "-metadata album='Kidz Bop' -metadata artist='Riley Snyder'" --download-archive /mnt/freezer/media/music/KidzBop/.log -o '/mnt/freezer/media/music/KidzBop/%(playlist_index)s-%(title)s.%(ext)s' https://www.youtube.com/playlist?list=PL1d05GXUOoNnkwFRPD8AS8OZhsL4Zy-BA

    - name: SmoothJelly
      shell:
        cmd: /home/riley/.local/bin/yt-dlp -i --extract-audio --audio-format mp3 --add-metadata --metadata-from-title "%(artist)s - %(title)s" --postprocessor-args "-metadata album='Smooth Jelly' -metadata artist='Riley Snyder'" --download-archive /mnt/freezer/media/music/SmoothJelly/.log -o '/mnt/freezer/media/music/SmoothJelly/%(playlist_index)s-%(title)s.%(ext)s' https://www.youtube.com/watch?v=hLQLu14maGk&list=PLel8KdUkdX_62mcYtZqsA0bQT2XgbOafe

    - name: The Fudge Bear
      shell:
        cmd: /home/riley/.local/bin/yt-dlp -i --extract-audio --audio-format mp3 ---add-metadata --metadata-from-title "%(artist)s - %(title)s" -postprocessor-args "-metadata album='The Fudge Bear' -metadata artist='Brody Smith'" --download-archive /mnt/freezer/media/music/TheFudgeBear/.log -o '/mnt/freezer/media/music/TheFudgeBear/%(playlist_index)s-%(title)s.%(ext)s' https://www.youtube.com/playlist?list=PL1d05GXUOoNlkCCkg2IZhUVPtTn6OuDCI
