---
version: "3"
services:

  nginx:
    image: library/nginx
    restart: unless-stopped
    ports:
      - 8888:80

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    volumes:
      - $APPDATA/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
