logLevel: DEBUG

fullnameOverride: ff-proxy

proxyKey: <+secrets.getValue("PROXY_KEY")>

authSecret: <+secrets.getValue("AUTH_SECRET")>

redis:
  address: redis.redis:6379

image:
  repository: <+artifacts.primary.imagePath>
  tag: <+artifacts.primary.tag>

writer:
  service:
    enabled: true
    type: LoadBalancer

  resources:
    limits:
      memory: 1G
    requests:
      cpu: 0.1
      memory: 10Mi
    
  podAnnotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "7000"
    prometheus.io/scrape: "true"

readReplica:
  service:
    type: LoadBalancer

  resources:
    limits:
      memory: 1G
    requests:
      cpu: 0.1
      memory: 10Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  ingress:
    enabled: false
    hosts:
      - host: ff-proxy-read-replica.k8s.rileysnyder.dev
        paths:
          - path: /
            pathType: Prefix

  podAnnotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "7000"
    prometheus.io/scrape: "true"