# apiVersion: v1
# kind: Namespace
# metadata:
#   name: ff-test

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: ff-test-v1
#   namespace: ff-test
#   labels:
#     app: ff-test-v1
# data:
#   RELAY_PROXY_ADDRESS: http://ff-relay-proxy-og.ff-relay-proxy-og.svc.cluster.local:7000
#   FF_SDK_KEY: 7689ce22-c50b-429b-9d30-34a74544eab1
#   FF_IDENTIFIER: test

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ff-test-v1
#   namespace: ff-test
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ff-test-v1
#   template:
#     metadata:
#       labels:
#         app: ff-test-v1
#     spec:
#       containers:
#       - name: ff-test-v1
#         image: harnesscommunity/feature-flag-relay-proxy-test:latest
#         imagePullPolicy: IfNotPresent
#         envFrom:
#         - configMapRef:
#             name: ff-test-v1
